/// Transpiles the official `@mysten/deepbook-v3` generated Move bindings
/// (`src/contracts` TS files, produced by @mysten/codegen) into Dart under
/// `lib/src/contracts/`.
///
/// The TS inputs are machine-generated with a rigid grammar, which this tool
/// parses structurally (no JS evaluation):
///   - `export const X = new MoveStruct({name, fields: {...}})`
///   - `export const X = new MoveTuple({name, fields: [...]})`
///   - `export function X<K...>(...typeParameters: [K...]) { new MoveStruct }`
///   - `export function x(options) { ... tx.moveCall({...}) }` builders with
///     `argumentsTypes` / `parameterNames`
///
/// Usage: `dart tool/codegen/generate.dart <ts-contracts-dir> [--out <dir>]`
/// Anything it cannot parse is a hard error, so upstream format drift is
/// caught instead of silently mistranslated.
library;

import 'dart:io';

const generatedHeader = '''
// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import
''';

const dartReserved = {
  'assert',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'default',
  'do',
  'else',
  'enum',
  'extends',
  'false',
  'final',
  'finally',
  'for',
  'if',
  'in',
  'is',
  'new',
  'null',
  'rethrow',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'var',
  'void',
  'while',
  'with',
};

String dartName(String tsName) {
  var name = tsName;
  if (name.startsWith('_')) name = name.substring(1); // TS `_new` → `new`
  if (dartReserved.contains(name)) name = '${name}_';
  return name;
}

/// Built-in identifiers that cannot be used as import prefixes.
const dartBuiltIns = {
  'abstract',
  'as',
  'covariant',
  'deferred',
  'dynamic',
  'export',
  'extension',
  'external',
  'factory',
  'function',
  'get',
  'implements',
  'import',
  'interface',
  'late',
  'library',
  'mixin',
  'operator',
  'part',
  'required',
  'set',
  'static',
  'typedef',
};

String dartAlias(String tsAlias) {
  var alias = tsAlias.replaceFirst(RegExp(r'^_+'), '');
  if (dartReserved.contains(alias) || dartBuiltIns.contains(alias)) {
    alias = '${alias}_';
  }
  return alias;
}

void main(List<String> argv) {
  if (argv.isEmpty) {
    stderr.writeln(
        'usage: dart tool/codegen/generate.dart <ts-contracts-dir> [--out <dir>]');
    exit(2);
  }
  final srcRoot = Directory(argv[0]);
  var outRoot = Directory('lib/src/contracts');
  final outIdx = argv.indexOf('--out');
  if (outIdx != -1) outRoot = Directory(argv[outIdx + 1]);

  final files = srcRoot
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.ts'))
      .where((f) => !f.path.endsWith('utils/index.ts'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  var structs = 0, tuples = 0, generics = 0, functions = 0;
  for (final file in files) {
    final rel = file.path
        .substring(srcRoot.path.length)
        .replaceFirst(RegExp(r'^/'), '')
        .replaceFirst(RegExp(r'\.ts$'), '.dart');
    final out = File('${outRoot.path}/$rel');
    final result = transpile(file.readAsStringSync(), rel, file.path);
    out.parent.createSync(recursive: true);
    out.writeAsStringSync(result.code);
    structs += result.structs;
    tuples += result.tuples;
    generics += result.generics;
    functions += result.functions;
  }
  stdout.writeln('${files.length} files → ${outRoot.path}: '
      '$structs structs, $tuples tuples, $generics generic structs, '
      '$functions function builders');
}

class TranspileResult {
  final String code;
  int structs = 0, tuples = 0, generics = 0, functions = 0;
  TranspileResult(this.code);
}

class Ctx {
  final String tsPath; // for error messages
  final String relPath; // dart-relative, e.g. deepbook/pool.dart
  final Map<String, String> importAliases = {}; // dart alias → import path
  final Map<String, String> aliasRenames = {}; // ts alias → dart alias
  final Set<String> localGenericStructs = {};
  Ctx(this.tsPath, this.relPath);
}

Never fail(Ctx ctx, String message) =>
    throw StateError('${ctx.tsPath}: $message');

TranspileResult transpile(String src, String relPath, String tsPath) {
  final ctx = Ctx(tsPath, relPath);
  final body = StringBuffer();
  var structs = 0, tuples = 0, generics = 0, functions = 0;

  // ---- module name -------------------------------------------------------
  // Function-only modules (e.g. constants.ts) have no $moduleName. The
  // declaration may be line-wrapped by prettier.
  final moduleName =
      RegExp(r"const \$moduleName =\s*'([^']+)'").firstMatch(src)?.group(1);

  // ---- imports -----------------------------------------------------------
  for (final m
      in RegExp(r"import \* as (\w+) from '([^']+)';").allMatches(src)) {
    final alias = m.group(1)!;
    var path = m.group(2)!;
    if (!path.startsWith('.')) fail(ctx, 'unexpected bare import $path');
    path = path.replaceFirst(RegExp(r'\.js$'), '.dart');
    ctx.importAliases[dartAlias(alias)] = path;
    ctx.aliasRenames[alias] = dartAlias(alias);
  }

  // Pre-scan local generic struct names (declared as functions).
  for (final m in RegExp(r'export function ([A-Z]\w*)<').allMatches(src)) {
    ctx.localGenericStructs.add(m.group(1)!);
  }

  // ---- walk export declarations ------------------------------------------
  var i = 0;
  while (true) {
    final exportIdx = src.indexOf('\nexport ', i);
    final start = exportIdx == -1
        ? (src.startsWith('export ') && i == 0 ? 0 : -1)
        : exportIdx + 1;
    if (start == -1) break;
    i = start + 7;

    final doc = _precedingDoc(src, start);
    final rest = src.substring(start);

    if (rest.startsWith('export interface') || rest.startsWith('export type')) {
      continue;
    }

    final structM =
        RegExp(r'^export const (\w+) = new (MoveStruct|MoveTuple|MoveEnum)\(')
            .firstMatch(rest);
    if (structM != null) {
      final name = structM.group(1)!;
      final kind = structM.group(2)!;
      final objSrc = _balancedSlice(rest, rest.indexOf('('), '(', ')');
      if (kind == 'MoveEnum') fail(ctx, 'MoveEnum not supported ($name)');
      body.write(_emitStruct(ctx, name, kind, objSrc, doc,
          generic: false, typeParamCount: 0));
      if (kind == 'MoveStruct') {
        structs++;
      } else {
        tuples++;
      }
      continue;
    }

    final genericM = RegExp(
            r'^export function ([A-Z]\w*)<[^(]*\(\s*\.\.\.typeParameters: \[([^\]]*)\]')
        .firstMatch(rest);
    if (genericM != null) {
      final name = genericM.group(1)!;
      final typeParamCount = genericM
          .group(2)!
          .split(',')
          .where((s) => s.trim().isNotEmpty)
          .length;
      final fnBody = _balancedSlice(rest, rest.indexOf('{'), '{', '}');
      final newIdx = fnBody.indexOf('new MoveStruct(');
      if (newIdx == -1) fail(ctx, 'generic struct $name: no MoveStruct');
      final objSrc =
          _balancedSlice(fnBody, fnBody.indexOf('(', newIdx + 4), '(', ')');
      body.write(_emitStruct(ctx, name, 'MoveStruct', objSrc, doc,
          generic: true, typeParamCount: typeParamCount));
      generics++;
      continue;
    }

    final fnM = RegExp(r'^export function (\w+)\s*[<(]').firstMatch(rest);
    if (fnM != null) {
      // Skip past the parameter list — default values like `= {}` would
      // otherwise be mistaken for the function body.
      final parenOpen = rest.indexOf('(');
      final params = _balancedSlice(rest, parenOpen, '(', ')');
      final bodyStart = rest.indexOf('{', parenOpen + params.length + 2);
      final fnBody = _balancedSlice(rest, bodyStart, '{', '}');
      body.write(_emitFunctionBuilder(ctx, fnM.group(1)!, fnBody, doc));
      functions++;
      continue;
    }

    if (rest.startsWith('export const')) {
      fail(ctx, 'unrecognized export const: ${rest.substring(0, 60)}');
    }
  }

  // ---- header ------------------------------------------------------------
  final depth = relPath.split('/').length - 1;
  final up = '../' * depth;
  final header = StringBuffer()
    ..writeln(generatedHeader)
    ..writeln("import 'package:bcs/bcs.dart';")
    ..writeln("import 'package:sui/bcs/sui_bcs.dart';")
    ..writeln("import 'package:sui/sui.dart' show Transaction;")
    ..writeln("import '${up}utils.dart';");
  for (final e in ctx.importAliases.entries) {
    header.writeln("import '${e.value}' as ${e.key};");
  }
  header.writeln();
  if (moduleName != null) {
    header.writeln("const \$moduleName = '$moduleName';");
  }

  final result = TranspileResult('$header\n$body');
  result.structs = structs;
  result.tuples = tuples;
  result.generics = generics;
  result.functions = functions;
  return result;
}

/// Doc comment (`/** … */`) immediately preceding offset [at], as `///` lines.
String _precedingDoc(String src, int at) {
  final before = src.substring(0, at);
  final m = RegExp(r'/\*\*((?:[^*]|\*(?!/))*)\*/\s*$').firstMatch(before);
  if (m == null) return '';
  final lines = m
      .group(1)!
      .split('\n')
      .map((l) => l.trim().replaceFirst(RegExp(r'^\*\s?'), '').trimRight())
      .toList();
  while (lines.isNotEmpty && lines.first.isEmpty) {
    lines.removeAt(0);
  }
  while (lines.isNotEmpty && lines.last.isEmpty) {
    lines.removeLast();
  }
  if (lines.isEmpty) return '';
  return '${lines.map((l) => l.isEmpty ? '///' : '/// $l').join('\n')}\n';
}

/// The text of a balanced bracket group starting at [openIdx] (inclusive
/// brackets stripped). Skips brackets inside string literals.
String _balancedSlice(String src, int openIdx, String open, String close) {
  var depth = 0;
  String? inString;
  for (var i = openIdx; i < src.length; i++) {
    final c = src[i];
    if (inString != null) {
      if (c == r'\') {
        i++;
      } else if (c == inString) {
        inString = null;
      }
      continue;
    }
    if (c == "'" || c == '"' || c == '`') {
      inString = c;
    } else if (c == open) {
      depth++;
    } else if (c == close) {
      depth--;
      if (depth == 0) return src.substring(openIdx + 1, i);
    }
  }
  throw StateError('unbalanced $open$close starting at $openIdx');
}

/// Removes `/* … */` blocks and whole-line `//` comments (generated files
/// never contain string literals that could be confused with comments here).
String _stripComments(String src) => src
    .replaceAll(RegExp(r'/\*(?:[^*]|\*(?!/))*\*/', dotAll: true), '')
    .split('\n')
    .where((l) => !l.trim().startsWith('//'))
    .join('\n');

/// Splits [src] on top-level commas (ignoring commas inside brackets/strings).
List<String> _splitTopLevel(String src) {
  final parts = <String>[];
  var depth = 0;
  String? inString;
  var current = StringBuffer();
  for (var i = 0; i < src.length; i++) {
    final c = src[i];
    if (inString != null) {
      current.write(c);
      if (c == r'\') {
        if (i + 1 < src.length) current.write(src[++i]);
      } else if (c == inString) {
        inString = null;
      }
      continue;
    }
    if (c == "'" || c == '"' || c == '`') {
      inString = c;
      current.write(c);
    } else if ('([{<'.contains(c)) {
      depth++;
      current.write(c);
    } else if (')]}>'.contains(c)) {
      depth--;
      current.write(c);
    } else if (c == ',' && depth == 0) {
      parts.add(current.toString().trim());
      current = StringBuffer();
    } else {
      current.write(c);
    }
  }
  final last = current.toString().trim();
  if (last.isNotEmpty) parts.add(last);
  return parts;
}

/// `${$moduleName}::X<${typeParameters[0].name as K['name']}>` (backtick
/// template) → Dart single-quoted interpolated string.
String _translateNameTemplate(Ctx ctx, String raw) {
  var s = raw.trim();
  if (s.startsWith('`') && s.endsWith('`')) s = s.substring(1, s.length - 1);
  if (s.startsWith("'") && s.endsWith("'")) s = s.substring(1, s.length - 1);
  s = s.replaceAll(RegExp(r" as \w+\['name'\]"), '');
  s = s.replaceAllMapped(RegExp(r'\$\{typeParameters\[(\d+)\]\.name\}'),
      (m) => '\${t${m.group(1)}.name}');
  s = s.replaceAll(r'${$moduleName}', r'${$moduleName}');
  if (RegExp(r'\$\{(?!\$moduleName\}|t\d+\.name\})').hasMatch(s)) {
    fail(ctx, 'unsupported name template: $raw');
  }
  return "'$s'";
}

/// Translates a TS BCS field-value expression into Dart.
String _translateBcsExpr(Ctx ctx, String expr) {
  final e = expr.trim();

  // bcs.<builtin>
  final bcsM = RegExp(r'^bcs\.(\w+)(\(.*\))?$', dotAll: true).firstMatch(e);
  if (bcsM != null) {
    final name = bcsM.group(1)!;
    final hasCall = bcsM.group(2) != null;
    final args = hasCall
        ? _splitTopLevel(_balancedSlice(e, e.indexOf('('), '(', ')'))
        : const <String>[];
    switch (name) {
      case 'u8':
        return 'SuiBcs.U8';
      case 'u16':
        return 'SuiBcs.U16';
      case 'u32':
        return 'SuiBcs.U32';
      case 'u64':
        return 'SuiBcs.U64';
      case 'u128':
        return 'SuiBcs.U128';
      case 'u256':
        return 'SuiBcs.U256';
      case 'bool':
      case 'Bool':
        return 'SuiBcs.BOOL';
      case 'string':
      case 'String':
        return 'SuiBcs.STRING';
      case 'Address':
        return 'SuiBcs.Address';
      case 'vector':
        if (args.length != 1) fail(ctx, 'vector arity: $e');
        return 'Bcs.vector(${_translateBcsExpr(ctx, args[0])})';
      case 'option':
        if (args.length != 1) fail(ctx, 'option arity: $e');
        return 'Bcs.option(${_translateBcsExpr(ctx, args[0])})';
      default:
        fail(ctx, 'unknown bcs.$name in $e');
    }
  }

  // typeParameters[N]
  final tpM = RegExp(r'^typeParameters\[(\d+)\]$').firstMatch(e);
  if (tpM != null) return 't${tpM.group(1)}';

  // <alias>.<Name>(...) | <alias>.<Name> | <Name>(...) | <Name>
  final refM = RegExp(r'^(?:(\w+)\.)?([A-Za-z_]\w*)(\(.*\))?$', dotAll: true)
      .firstMatch(e);
  if (refM != null) {
    final tsAlias = refM.group(1);
    final alias = tsAlias == null ? null : ctx.aliasRenames[tsAlias];
    final name = refM.group(2)!;
    final hasCall = refM.group(3) != null;
    if (tsAlias != null && alias == null) {
      fail(ctx, 'unknown alias $tsAlias in $e');
    }
    final target = alias != null ? '$alias.$name' : name;
    if (!hasCall) return target;
    final args = _splitTopLevel(_balancedSlice(e, e.indexOf('('), '(', ')'))
        .map((a) => _translateBcsExpr(ctx, a))
        .join(', ');
    return '$target($args)';
  }

  fail(ctx, 'unsupported bcs expression: $expr');
}

String _emitStruct(
  Ctx ctx,
  String name,
  String kind,
  String objSrc,
  String doc, {
  required bool generic,
  required int typeParamCount,
}) {
  final nameField =
      RegExp(r'name:\s*(`[^`]*`|' r"'[^']*')", dotAll: true).firstMatch(objSrc);
  if (nameField == null) fail(ctx, 'struct $name: missing name');
  final nameExpr = _translateNameTemplate(ctx, nameField.group(1)!);

  final fieldsIdx = objSrc.indexOf('fields:');
  if (fieldsIdx == -1) fail(ctx, 'struct $name: missing fields');
  String schemaExpr;
  if (kind == 'MoveTuple') {
    final listSrc = _stripComments(
        _balancedSlice(objSrc, objSrc.indexOf('[', fieldsIdx), '[', ']'));
    final items = _splitTopLevel(listSrc)
        .map((e) => _translateBcsExpr(ctx, e))
        .join(', ');
    schemaExpr = 'Bcs.tuple([$items], BcsTypeOptions(name: $nameExpr))';
  } else {
    final mapSrc = _stripComments(
        _balancedSlice(objSrc, objSrc.indexOf('{', fieldsIdx), '{', '}'));
    final entries = _splitTopLevel(mapSrc).where((s) => s.isNotEmpty).map((s) {
      final colon = s.indexOf(':');
      if (colon == -1) fail(ctx, 'struct $name: bad field entry $s');
      final key = s.substring(0, colon).trim();
      final value = _translateBcsExpr(ctx, s.substring(colon + 1));
      return "    '$key': $value,";
    }).join('\n');
    schemaExpr = "Bcs.struct($nameExpr, {\n$entries\n  })";
  }

  if (!generic) {
    return '$doc'
        'final $name = $schemaExpr;\n\n';
  }
  final params =
      List.generate(typeParamCount, (n) => 'BcsType<dynamic, dynamic> t$n')
          .join(', ');
  return '$doc'
      'BcsType<Map<String, dynamic>, dynamic> $name($params) =>\n'
      '  $schemaExpr;\n\n';
}

String _emitFunctionBuilder(Ctx ctx, String tsName, String fnBody, String doc) {
  final name = dartName(tsName);

  final pkgM = RegExp(r"options\.package \?\? '([^']+)'").firstMatch(fnBody);
  if (pkgM == null) fail(ctx, 'builder $tsName: missing default package');
  final defaultPackage = pkgM.group(1)!;

  final moduleM = RegExp(r"module:\s*'([^']+)'").firstMatch(fnBody);
  final functionM = RegExp(r"function:\s*'([^']+)'").firstMatch(fnBody);
  if (moduleM == null || functionM == null) {
    fail(ctx, 'builder $tsName: missing module/function');
  }
  final moveModule = moduleM.group(1)!;
  final moveFunction = functionM.group(1)!;

  // argumentsTypes (may be absent for zero-arg builders)
  List<String> argTypeExprs = const [];
  final argTypesIdx = fnBody.indexOf('const argumentsTypes = [');
  if (argTypesIdx != -1) {
    final listSrc =
        _balancedSlice(fnBody, fnBody.indexOf('[', argTypesIdx), '[', ']');
    argTypeExprs = _splitTopLevel(listSrc).map((raw) {
      final e = raw.trim();
      if (e == 'null') return 'null';
      if (e.startsWith("'")) return e; // plain Move type string
      if (e.startsWith('`')) {
        final t = e.substring(1, e.length - 1);
        final soleM =
            RegExp(r'^\$\{options\.typeArguments\[(\d+)\]\}$').firstMatch(t);
        if (soleM != null) return 'typeArguments[${soleM.group(1)}]';
        final mapped = t.replaceAllMapped(
            RegExp(r'\$\{options\.typeArguments\[(\d+)\]\}'),
            (m) => '\${typeArguments[${m.group(1)}]}');
        if (mapped.contains(r'${options.')) {
          fail(ctx, 'builder $tsName: unsupported argType template $raw');
        }
        return "'$mapped'";
      }
      fail(ctx, 'builder $tsName: unsupported argType $raw');
    }).toList();
  }

  // parameterNames (absent when the builder takes no user arguments)
  List<String> paramNames = const [];
  final paramNamesIdx = fnBody.indexOf('const parameterNames = [');
  if (paramNamesIdx != -1) {
    final listSrc =
        _balancedSlice(fnBody, fnBody.indexOf('[', paramNamesIdx), '[', ']');
    paramNames = _splitTopLevel(listSrc)
        .map((e) => e.trim().replaceAll("'", ''))
        .toList();
  }

  final usesTypeArguments = fnBody.contains('options.typeArguments');
  final hasArguments = fnBody.contains('normalizeMoveArguments');

  final params = <String>[];
  if (hasArguments && paramNames.isNotEmpty) {
    params.add('required dynamic arguments');
  }
  params.add('String? package');
  if (usesTypeArguments) {
    params.add('List<String> typeArguments = const []');
  }

  final argTypesList = '[${argTypeExprs.join(', ')}]';
  final paramNamesList = '[${paramNames.map((n) => "'$n'").join(', ')}]';

  final buf = StringBuffer()
    ..write(doc)
    ..writeln('MoveCallBuilder $name({${params.join(', ')}}) {')
    ..writeln("  final packageAddress = package ?? '$defaultPackage';")
    ..writeln('  return (tx) => tx.moveCall(')
    ..writeln("        '\$packageAddress::$moveModule::$moveFunction',");
  if (usesTypeArguments) {
    buf.writeln('        typeArguments: typeArguments,');
  }
  if (hasArguments) {
    final argsExpr =
        paramNames.isNotEmpty ? 'arguments' : 'const <String, dynamic>{}';
    buf.writeln(
        '        arguments: normalizeMoveArguments(tx, $argsExpr, $argTypesList, $paramNamesList),');
  }
  buf
    ..writeln('      );')
    ..writeln('}')
    ..writeln();
  return buf.toString();
}
