// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';

MoveCallBuilder marginVersion({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::margin_version',
      );
}

MoveCallBuilder maxRiskRatio({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::max_risk_ratio',
      );
}

MoveCallBuilder defaultUserLiquidationReward({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::default_user_liquidation_reward',
      );
}

MoveCallBuilder defaultPoolLiquidationReward({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::default_pool_liquidation_reward',
      );
}

MoveCallBuilder minLeverage({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::min_leverage',
      );
}

MoveCallBuilder maxLeverage({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::max_leverage',
      );
}

MoveCallBuilder yearMs({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::year_ms',
      );
}

MoveCallBuilder minMinBorrow({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::min_min_borrow',
      );
}

MoveCallBuilder maxMarginManagers({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::max_margin_managers',
      );
}

MoveCallBuilder defaultReferral({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::default_referral',
      );
}

MoveCallBuilder maxProtocolSpread({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::max_protocol_spread',
      );
}

MoveCallBuilder minLiquidationRepay({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::min_liquidation_repay',
      );
}

MoveCallBuilder maxConfBps({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::max_conf_bps',
      );
}

MoveCallBuilder maxEwmaDifferenceBps({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::max_ewma_difference_bps',
      );
}

MoveCallBuilder maxConditionalOrders({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::max_conditional_orders',
      );
}

MoveCallBuilder dayMs({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::day_ms',
      );
}

MoveCallBuilder defaultMaxPriceAgeMs({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::default_max_price_age_ms',
      );
}

MoveCallBuilder defaultPriceTolerance({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::default_price_tolerance',
      );
}

MoveCallBuilder minPriceAgeMs({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::min_price_age_ms',
      );
}

MoveCallBuilder maxPriceAgeMs({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::max_price_age_ms',
      );
}

MoveCallBuilder minPriceTolerance({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::min_price_tolerance',
      );
}

MoveCallBuilder maxPriceTolerance({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::max_price_tolerance',
      );
}

MoveCallBuilder defaultMaxOrderTtlMs({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::default_max_order_ttl_ms',
      );
}

MoveCallBuilder minMaxOrderTtlMs({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::min_max_order_ttl_ms',
      );
}

MoveCallBuilder maxMaxOrderTtlMs({String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_constants::max_max_order_ttl_ms',
      );
}
