// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/deepbook/balance_manager.dart' as balance_manager;
import './tpsl.dart' as tpsl;
import './deps/sui/vec_map.dart' as vec_map;
import './deps/std/type_name.dart' as type_name;

const $moduleName = '@deepbook/margin::margin_manager';

final MarginApp = Bcs.struct('${$moduleName}::MarginApp', {
  'dummy_field': SuiBcs.BOOL,
});

final MarginManager = Bcs.struct(
    '${$moduleName}::MarginManager<phantom BaseAsset, phantom QuoteAsset>', {
  'id': SuiBcs.Address,
  'owner': SuiBcs.Address,
  'deepbook_pool': SuiBcs.Address,
  'margin_pool_id': Bcs.option(SuiBcs.Address),
  'balance_manager': balance_manager.BalanceManager,
  'deposit_cap': balance_manager.DepositCap,
  'withdraw_cap': balance_manager.WithdrawCap,
  'trade_cap': balance_manager.TradeCap,
  'borrowed_base_shares': SuiBcs.U64,
  'borrowed_quote_shares': SuiBcs.U64,
  'take_profit_stop_loss': tpsl.TakeProfitStopLoss,
  'extra_fields': vec_map.VecMap(SuiBcs.STRING, SuiBcs.U64),
});

final ManagerInitializer = Bcs.struct('${$moduleName}::ManagerInitializer', {
  'margin_manager_id': SuiBcs.Address,
});

final MarginManagerCreatedEvent =
    Bcs.struct('${$moduleName}::MarginManagerCreatedEvent', {
  'margin_manager_id': SuiBcs.Address,
  'balance_manager_id': SuiBcs.Address,
  'deepbook_pool_id': SuiBcs.Address,
  'owner': SuiBcs.Address,
  'timestamp': SuiBcs.U64,
});

final LoanBorrowedEvent = Bcs.struct('${$moduleName}::LoanBorrowedEvent', {
  'margin_manager_id': SuiBcs.Address,
  'margin_pool_id': SuiBcs.Address,
  'loan_amount': SuiBcs.U64,
  'loan_shares': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

final LoanRepaidEvent = Bcs.struct('${$moduleName}::LoanRepaidEvent', {
  'margin_manager_id': SuiBcs.Address,
  'margin_pool_id': SuiBcs.Address,
  'repay_amount': SuiBcs.U64,
  'repay_shares': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

final LiquidationEvent = Bcs.struct('${$moduleName}::LiquidationEvent', {
  'margin_manager_id': SuiBcs.Address,
  'margin_pool_id': SuiBcs.Address,
  'liquidation_amount': SuiBcs.U64,
  'pool_reward': SuiBcs.U64,
  'pool_default': SuiBcs.U64,
  'risk_ratio': SuiBcs.U64,
  'remaining_base_asset': SuiBcs.U64,
  'remaining_quote_asset': SuiBcs.U64,
  'remaining_base_debt': SuiBcs.U64,
  'remaining_quote_debt': SuiBcs.U64,
  'base_pyth_price': SuiBcs.U64,
  'base_pyth_decimals': SuiBcs.U8,
  'quote_pyth_price': SuiBcs.U64,
  'quote_pyth_decimals': SuiBcs.U8,
  'timestamp': SuiBcs.U64,
});

final DepositCollateralEvent =
    Bcs.struct('${$moduleName}::DepositCollateralEvent', {
  'margin_manager_id': SuiBcs.Address,
  'amount': SuiBcs.U64,
  'asset': type_name.TypeName,
  'pyth_price': SuiBcs.U64,
  'pyth_decimals': SuiBcs.U8,
  'timestamp': SuiBcs.U64,
});

final WithdrawCollateralEvent =
    Bcs.struct('${$moduleName}::WithdrawCollateralEvent', {
  'margin_manager_id': SuiBcs.Address,
  'amount': SuiBcs.U64,
  'asset': type_name.TypeName,
  'withdraw_base_asset': SuiBcs.BOOL,
  'remaining_base_asset': SuiBcs.U64,
  'remaining_quote_asset': SuiBcs.U64,
  'remaining_base_debt': SuiBcs.U64,
  'remaining_quote_debt': SuiBcs.U64,
  'base_pyth_price': SuiBcs.U64,
  'base_pyth_decimals': SuiBcs.U8,
  'quote_pyth_price': SuiBcs.U64,
  'quote_pyth_decimals': SuiBcs.U8,
  'timestamp': SuiBcs.U64,
});

/// Add a conditional order (take-profit / stop-loss). Specifies the condition under
/// which it triggers and the pending order to place when it does.
///
/// Lifetime: the conditional order itself is never clamped — it rests in the queue
/// until it triggers or is cancelled. A _market_ pending order
/// (`tpsl::new_pending_market_order`) has no expiry, so it is the "until cancelled"
/// stop: it waits indefinitely and, when triggered, fires and deleverages via
/// `execute_conditional_orders_v3` (so it can protect even in the danger band). A
/// _limit_ pending order is intentionally transient — when it triggers, the resting
/// order it places is clamped to `max_order_ttl_ms` (default 3 days) by
/// `clamp_expire_timestamp`, the same stale-price guard as any margin limit order.
/// For a permanent stop, use a market pending order.
MoveCallBuilder addConditionalOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::add_conditional_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          'u64',
          null,
          null,
          '0x2::clock::Clock'
        ], [
          'self',
          'pool',
          'basePriceInfoObject',
          'quotePriceInfoObject',
          'registry',
          'conditionalOrderId',
          'condition',
          'pendingOrder'
        ]),
      );
}

/// Cancel all conditional orders.
MoveCallBuilder cancelAllConditionalOrders(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::cancel_all_conditional_orders',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, '0x2::clock::Clock'], ['self']),
      );
}

/// Cancel a conditional order.
MoveCallBuilder cancelConditionalOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::cancel_conditional_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments,
            [null, 'u64', '0x2::clock::Clock'], ['self', 'conditionalOrderId']),
      );
}

/// DEPRECATED. Use `execute_conditional_orders_v2`.
///
/// The v1 entry preserves its on-chain signature so the v5 package upgrade
/// type-checks against existing dependents, but the body is replaced with
/// `abort EDeprecatedUseV2`. The v2 variant adds margin-pool + oracle params and
/// enforces a post-fill `risk_ratio >= min_borrow_risk_ratio` invariant inside
/// `process_collected_orders_v2`.
MoveCallBuilder executeConditionalOrders(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::execute_conditional_orders',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          'u64',
          '0x2::clock::Clock'
        ], [
          'Self',
          'Pool',
          'BasePriceInfoObject',
          'QuotePriceInfoObject',
          'Registry',
          'MaxOrdersToExecute'
        ]),
      );
}

/// Execute conditional orders and return the order infos. This is a permissionless
/// function that can be called by anyone.
///
/// v2 adds `base_margin_pool` + `quote_margin_pool` parameters and enforces a
/// post-fill `risk_ratio >= min_borrow_risk_ratio` invariant inside the inner loop.
/// If any single triggered fill would breach that floor, the entire txn aborts — no
/// partial-state landing.
MoveCallBuilder executeConditionalOrdersV2(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::execute_conditional_orders_v2',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          'u64',
          '0x2::clock::Clock'
        ], [
          'self',
          'pool',
          'baseMarginPool',
          'quoteMarginPool',
          'basePriceInfoObject',
          'quotePriceInfoObject',
          'registry',
          'maxOrdersToExecute'
        ]),
      );
}

/// Execute conditional orders, deleveraging on each market-type fill.
/// Permissionless, like `execute_conditional_orders_v2`, with the same trigger and
/// cancellation handling — but takes the margin pools as `&mut` and repays the loan
/// with the market proceeds before gating on the net (post-repay) `risk_ratio`
/// being at least the pre-fill ratio.
///
/// This is what lets a stop-loss fire in the `liquidation..min_borrow` danger band:
/// a swap alone only lowers the oracle-valued ratio (so the v2 borrow-floor gate
/// rejects it), while repaying actually improves it. If a single triggered fill
/// would worsen net solvency the whole txn aborts — no partial-state landing.
MoveCallBuilder executeConditionalOrdersV3(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::execute_conditional_orders_v3',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          'u64',
          '0x2::clock::Clock'
        ], [
          'self',
          'pool',
          'baseMarginPool',
          'quoteMarginPool',
          'basePriceInfoObject',
          'quotePriceInfoObject',
          'registry',
          'maxOrdersToExecute'
        ]),
      );
}

/// Creates a new margin manager and shares it.
MoveCallBuilder new_(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::new',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, '0x2::clock::Clock'],
            ['pool', 'deepbookRegistry', 'marginRegistry']),
      );
}

/// Creates a new margin manager and returns it along with an initializer. The
/// initializer is used to ensure the margin manager is shared after creation.
MoveCallBuilder newWithInitializer(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::new_with_initializer',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, '0x2::clock::Clock'],
            ['pool', 'deepbookRegistry', 'marginRegistry']),
      );
}

/// Shares the margin manager. The initializer is dropped in the process.
MoveCallBuilder share(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::share',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['manager', 'initializer']),
      );
}

/// Register the margin manager back to the margin registry.
MoveCallBuilder registerMarginManager(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::register_margin_manager',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'marginRegistry']),
      );
}

/// Unregister the margin manager from the margin registry.
MoveCallBuilder unregisterMarginManager(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::unregister_margin_manager',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'marginRegistry']),
      );
}

/// Set the referral for the margin manager.
MoveCallBuilder setMarginManagerReferral(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::set_margin_manager_referral',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'referralCap']),
      );
}

/// Unset the referral for the margin manager.
MoveCallBuilder unsetMarginManagerReferral(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::unset_margin_manager_referral',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, '0x2::object::ID'], ['self', 'poolId']),
      );
}

/// Deposit a coin into the margin manager. The coin must be of the same type as
/// either the base, quote, or DEEP.
MoveCallBuilder deposit(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::deposit',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, null, null, '0x2::clock::Clock'],
            ['self', 'registry', 'baseOracle', 'quoteOracle', 'coin']),
      );
}

/// Withdraw a specified amount of an asset from the margin manager. The asset must
/// be of the same type as either the base, quote, or DEEP. The withdrawal is
/// subject to the risk ratio limit.
MoveCallBuilder withdraw(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::withdraw',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          'u64',
          '0x2::clock::Clock'
        ], [
          'self',
          'registry',
          'baseMarginPool',
          'quoteMarginPool',
          'baseOracle',
          'quoteOracle',
          'pool',
          'withdrawAmount'
        ]),
      );
}

/// Borrow the base asset using the margin manager.
MoveCallBuilder borrowBase(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::borrow_base',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          'u64',
          '0x2::clock::Clock'
        ], [
          'self',
          'registry',
          'baseMarginPool',
          'baseOracle',
          'quoteOracle',
          'pool',
          'loanAmount'
        ]),
      );
}

/// Borrow the quote asset using the margin manager.
MoveCallBuilder borrowQuote(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::borrow_quote',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          'u64',
          '0x2::clock::Clock'
        ], [
          'self',
          'registry',
          'quoteMarginPool',
          'baseOracle',
          'quoteOracle',
          'pool',
          'loanAmount'
        ]),
      );
}

/// Repay the base asset loan using the margin manager. Returns the total amount
/// repaid
MoveCallBuilder repayBase(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::repay_base',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, '0x1::option::Option<u64>', '0x2::clock::Clock'],
            ['self', 'registry', 'marginPool', 'amount']),
      );
}

/// Repay the quote asset loan using the margin manager. Returns the total amount
/// repaid
MoveCallBuilder repayQuote(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::repay_quote',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, '0x1::option::Option<u64>', '0x2::clock::Clock'],
            ['self', 'registry', 'marginPool', 'amount']),
      );
}

MoveCallBuilder liquidate(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::liquidate',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          '0x2::clock::Clock'
        ], [
          'self',
          'registry',
          'baseOracle',
          'quoteOracle',
          'marginPool',
          'pool',
          'repayCoin'
        ]),
      );
}

MoveCallBuilder riskRatio(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::risk_ratio',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          '0x2::clock::Clock'
        ], [
          'self',
          'registry',
          'baseOracle',
          'quoteOracle',
          'pool',
          'baseMarginPool',
          'quoteMarginPool'
        ]),
      );
}

/// Returns the risk ratio without validating oracle price staleness or confidence.
/// Use for read-only queries where stale prices are acceptable.
MoveCallBuilder riskRatioUnsafe(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::risk_ratio_unsafe',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          '0x2::clock::Clock'
        ], [
          'self',
          'registry',
          'baseOracle',
          'quoteOracle',
          'pool',
          'baseMarginPool',
          'quoteMarginPool'
        ]),
      );
}

MoveCallBuilder balanceManager(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::balance_manager',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder baseBalance(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::base_balance',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder quoteBalance(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::quote_balance',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder deepBalance(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::deep_balance',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Returns (base_asset, quote_asset) for margin manager.
MoveCallBuilder calculateAssets(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::calculate_assets',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'pool']),
      );
}

MoveCallBuilder calculateDebts(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::calculate_debts',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments,
            [null, null, '0x2::clock::Clock'], ['self', 'marginPool']),
      );
}

/// Returns comprehensive state information for a margin manager. Returns
/// (manager_id, deepbook_pool_id, risk_ratio, base_asset, quote_asset, base_debt,
/// quote_debt, base_pyth_price, base_pyth_decimals, quote_pyth_price,
/// quote_pyth_decimals, current_price, lowest_trigger_above_price,
/// highest_trigger_below_price)
MoveCallBuilder managerState(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::manager_state',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          '0x2::clock::Clock'
        ], [
          'self',
          'registry',
          'baseOracle',
          'quoteOracle',
          'pool',
          'baseMarginPool',
          'quoteMarginPool'
        ]),
      );
}

MoveCallBuilder id(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::id',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder owner(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::owner',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder deepbookPool(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::deepbook_pool',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder marginPoolId(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::margin_pool_id',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder borrowedShares(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::borrowed_shares',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder borrowedBaseShares(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::borrowed_base_shares',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder borrowedQuoteShares(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::borrowed_quote_shares',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder hasBaseDebt(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::has_base_debt',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder conditionalOrderIds(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::conditional_order_ids',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder conditionalOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::conditional_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, 'u64'], ['self', 'conditionalOrderId']),
      );
}

/// Returns the lowest trigger price for trigger_above orders Returns
/// constants::max_u64() if there are no trigger_above orders
MoveCallBuilder lowestTriggerAbovePrice(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::lowest_trigger_above_price',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Returns the highest trigger price for trigger_below orders Returns 0 if there
/// are no trigger_below orders
MoveCallBuilder highestTriggerBelowPrice(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::highest_trigger_below_price',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder getAccountOrderDetails(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::get_account_order_details',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'pool']),
      );
}

MoveCallBuilder accountOpenOrders(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::account_open_orders',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'pool']),
      );
}

MoveCallBuilder lockedBalance(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::locked_balance',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'pool']),
      );
}

MoveCallBuilder balanceManagerId(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::balance_manager_id',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder getBalanceManagerReferralId(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::get_balance_manager_referral_id',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, '0x2::object::ID'], ['self', 'poolId']),
      );
}

MoveCallBuilder accountExists(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::account_exists',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'pool']),
      );
}

MoveCallBuilder account(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::account',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'pool']),
      );
}

MoveCallBuilder canPlaceLimitOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::can_place_limit_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          'u64',
          'u64',
          'bool',
          'bool',
          'u64',
          '0x2::clock::Clock'
        ], [
          'self',
          'pool',
          'price',
          'quantity',
          'isBid',
          'payWithDeep',
          'expireTimestamp'
        ]),
      );
}

MoveCallBuilder canPlaceMarketOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_manager::can_place_market_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, 'u64', 'bool', 'bool', '0x2::clock::Clock'],
            ['self', 'pool', 'quantity', 'isBid', 'payWithDeep']),
      );
}
