// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/sui/versioned.dart' as versioned;
import './deps/sui/vec_set.dart' as vec_set;
import './deps/sui/table.dart' as table;
import './deps/sui/vec_map.dart' as vec_map;

const $moduleName = '@deepbook/margin::margin_registry';

final MARGIN_REGISTRY = Bcs.struct('${$moduleName}::MARGIN_REGISTRY', {
  'dummy_field': SuiBcs.BOOL,
});

final MarginRegistry = Bcs.struct('${$moduleName}::MarginRegistry', {
  'id': SuiBcs.Address,
  'inner': versioned.Versioned,
});

final MarginRegistryInner = Bcs.struct('${$moduleName}::MarginRegistryInner', {
  'registry_id': SuiBcs.Address,
  'allowed_versions': vec_set.VecSet(SuiBcs.U64),
  'pool_registry': table.Table,
  'margin_pools': table.Table,
  'margin_managers': table.Table,
  'allowed_maintainers': vec_set.VecSet(SuiBcs.Address),
  'allowed_pause_caps': vec_set.VecSet(SuiBcs.Address),
});

final RiskRatios = Bcs.struct('${$moduleName}::RiskRatios', {
  'min_withdraw_risk_ratio': SuiBcs.U64,
  'min_borrow_risk_ratio': SuiBcs.U64,
  'liquidation_risk_ratio': SuiBcs.U64,
  'target_liquidation_risk_ratio': SuiBcs.U64,
});

final PoolConfig = Bcs.struct('${$moduleName}::PoolConfig', {
  'base_margin_pool_id': SuiBcs.Address,
  'quote_margin_pool_id': SuiBcs.Address,
  'risk_ratios': RiskRatios,
  'user_liquidation_reward': SuiBcs.U64,
  'pool_liquidation_reward': SuiBcs.U64,
  'enabled': SuiBcs.BOOL,
  'extra_fields': vec_map.VecMap(SuiBcs.STRING, SuiBcs.U64),
});

final ConfigKey = Bcs.struct('${$moduleName}::ConfigKey<phantom Config>', {
  'dummy_field': SuiBcs.BOOL,
});

final CurrentPriceKey = Bcs.struct('${$moduleName}::CurrentPriceKey', {
  'pool_id': SuiBcs.Address,
});

final CurrentPriceData = Bcs.struct('${$moduleName}::CurrentPriceData', {
  'price': SuiBcs.U64,
  'last_price_update_ms': SuiBcs.U64,
  'tolerance': SuiBcs.U64,
  'max_price_age_ms': SuiBcs.U64,
});

final MaxOrderTtlKey = Bcs.tuple(
    [SuiBcs.Address], BcsTypeOptions(name: '${$moduleName}::MaxOrderTtlKey'));

final MinOpenRiskRatioKey = Bcs.tuple([SuiBcs.Address],
    BcsTypeOptions(name: '${$moduleName}::MinOpenRiskRatioKey'));

final MarginAdminCap = Bcs.struct('${$moduleName}::MarginAdminCap', {
  'id': SuiBcs.Address,
});

final MarginPauseCap = Bcs.struct('${$moduleName}::MarginPauseCap', {
  'id': SuiBcs.Address,
});

final MaintainerCap = Bcs.struct('${$moduleName}::MaintainerCap', {
  'id': SuiBcs.Address,
});

final MarginPoolCap = Bcs.struct('${$moduleName}::MarginPoolCap', {
  'id': SuiBcs.Address,
  'margin_pool_id': SuiBcs.Address,
});

final MaintainerCapUpdated =
    Bcs.struct('${$moduleName}::MaintainerCapUpdated', {
  'maintainer_cap_id': SuiBcs.Address,
  'allowed': SuiBcs.BOOL,
  'timestamp': SuiBcs.U64,
});

final PauseCapUpdated = Bcs.struct('${$moduleName}::PauseCapUpdated', {
  'pause_cap_id': SuiBcs.Address,
  'allowed': SuiBcs.BOOL,
  'timestamp': SuiBcs.U64,
});

final DeepbookPoolRegistered =
    Bcs.struct('${$moduleName}::DeepbookPoolRegistered', {
  'pool_id': SuiBcs.Address,
  'config': PoolConfig,
  'timestamp': SuiBcs.U64,
});

final DeepbookPoolUpdated = Bcs.struct('${$moduleName}::DeepbookPoolUpdated', {
  'pool_id': SuiBcs.Address,
  'enabled': SuiBcs.BOOL,
  'timestamp': SuiBcs.U64,
});

final DeepbookPoolConfigUpdated =
    Bcs.struct('${$moduleName}::DeepbookPoolConfigUpdated', {
  'pool_id': SuiBcs.Address,
  'config': PoolConfig,
  'timestamp': SuiBcs.U64,
});

final CurrentPriceUpdated = Bcs.struct('${$moduleName}::CurrentPriceUpdated', {
  'pool_id': SuiBcs.Address,
  'price': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

final PriceToleranceUpdated =
    Bcs.struct('${$moduleName}::PriceToleranceUpdated', {
  'pool_id': SuiBcs.Address,
  'tolerance': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

final MaxPriceAgeUpdated = Bcs.struct('${$moduleName}::MaxPriceAgeUpdated', {
  'pool_id': SuiBcs.Address,
  'max_age_ms': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

final MaxOrderTtlUpdated = Bcs.struct('${$moduleName}::MaxOrderTtlUpdated', {
  'pool_id': SuiBcs.Address,
  'max_order_ttl_ms': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

final MinOpenRiskRatioUpdated =
    Bcs.struct('${$moduleName}::MinOpenRiskRatioUpdated', {
  'pool_id': SuiBcs.Address,
  'min_open_risk_ratio': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

/// Mint a `MaintainerCap`, only admin can mint a `MaintainerCap`. This function
/// does not have version restrictions
MoveCallBuilder mintMaintainerCap(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::mint_maintainer_cap',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, null, '0x2::clock::Clock'], ['self', 'AdminCap']),
      );
}

/// Revoke a `MaintainerCap`. Only the admin can revoke a `MaintainerCap`. This
/// function does not have version restrictions
MoveCallBuilder revokeMaintainerCap(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::revoke_maintainer_cap',
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, '0x2::object::ID', '0x2::clock::Clock'],
            ['self', 'AdminCap', 'maintainerCapId']),
      );
}

/// Register a margin pool for margin trading with existing margin pools
MoveCallBuilder registerDeepbookPool(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::register_deepbook_pool',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, null, '0x2::clock::Clock'],
            ['self', 'AdminCap', 'pool', 'poolConfig']),
      );
}

/// Enables a deepbook pool for margin trading.
MoveCallBuilder enableDeepbookPool(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::enable_deepbook_pool',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, '0x2::clock::Clock'],
            ['self', 'AdminCap', 'pool']),
      );
}

/// Disables a deepbook pool from margin trading. Only reduce only orders, cancels,
/// and withdraw settled amounts are allowed.
MoveCallBuilder disableDeepbookPool(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::disable_deepbook_pool',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, '0x2::clock::Clock'],
            ['self', 'AdminCap', 'pool']),
      );
}

/// Updates risk params for a deepbook pool as the admin.
MoveCallBuilder updateRiskParams(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::update_risk_params',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, null, '0x2::clock::Clock'],
            ['self', 'AdminCap', 'pool', 'poolConfig']),
      );
}

/// Add Pyth Config to the MarginRegistry.
MoveCallBuilder addConfig(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::add_config',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments,
            [null, null, typeArguments[0]], ['self', 'AdminCap', 'config']),
      );
}

/// Remove Pyth Config from the MarginRegistry.
MoveCallBuilder removeConfig(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::remove_config',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'AdminCap']),
      );
}

/// Enables a package version Only Admin can enable a package version This function
/// does not have version restrictions
MoveCallBuilder enableVersion({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::enable_version',
        arguments: normalizeMoveArguments(tx, arguments, [null, 'u64', null],
            ['self', 'version', 'AdminCap']),
      );
}

/// Disables a package version Only Admin can disable a package version This
/// function does not have version restrictions
MoveCallBuilder disableVersion({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::disable_version',
        arguments: normalizeMoveArguments(tx, arguments, [null, 'u64', null],
            ['self', 'version', 'AdminCap']),
      );
}

/// Disables a package version Pause Cap must be valid and can disable the version
/// This function does not have version restrictions
MoveCallBuilder disableVersionPauseCap(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::disable_version_pause_cap',
        arguments: normalizeMoveArguments(tx, arguments, [null, 'u64', null],
            ['self', 'version', 'pauseCap']),
      );
}

/// Mint a pause cap Only Admin can mint a pause cap This function does not have
/// version restrictions
MoveCallBuilder mintPauseCap({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::mint_pause_cap',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, null, '0x2::clock::Clock'], ['self', 'AdminCap']),
      );
}

/// Revoke a pause cap Only Admin can revoke a pause cap This function does not have
/// version restrictions
MoveCallBuilder revokePauseCap({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::revoke_pause_cap',
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, '0x2::clock::Clock', '0x2::object::ID'],
            ['self', 'AdminCap', 'pauseCapId']),
      );
}

/// Set price deviation tolerance for a pool tolerance is in 9 decimals where 1.0 =
/// 1_000_000_000 (e.g., 100_000_000 = 0.1 = 10%) Only Admin can set tolerance
/// Requires price to be initialized first via update_current_price
MoveCallBuilder setPriceTolerance(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::set_price_tolerance',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'u64', '0x2::clock::Clock'],
            ['self', 'AdminCap', 'pool', 'tolerance']),
      );
}

/// Set maximum price age in milliseconds for a pool Only Admin can set max price
/// age Requires price to be initialized first via update_current_price
MoveCallBuilder setMaxPriceAge(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::set_max_price_age',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'u64', '0x2::clock::Clock'],
            ['self', 'AdminCap', 'pool', 'maxAgeMs']),
      );
}

/// Set the maximum lifetime (in ms) of margin limit orders for a pool.
/// User-supplied `expire_timestamp` on margin limit-order placements is clamped to
/// at most `now + max_order_ttl_ms`. Bounds margin orders' exposure to stale-price
/// exploitation if liquidity disappears after placement. Only Admin can set max
/// order TTL.
MoveCallBuilder setMaxOrderTtl(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::set_max_order_ttl',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'u64', '0x2::clock::Clock'],
            ['self', 'AdminCap', 'pool', 'maxOrderTtlMs']),
      );
}

/// Set the per-pool `min_open_risk_ratio` override — the post-trade solvency floor
/// enforced on opening (risk-increasing) orders. Must sit in
/// `(liquidation_risk_ratio, min_borrow_risk_ratio]`: above liquidation so an open
/// can't land in the liquidatable zone, at or below the borrow floor. Absent an
/// override the floor defaults to the midpoint of liquidation and min_borrow. Only
/// Admin can set it.
MoveCallBuilder setMinOpenRiskRatio(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::set_min_open_risk_ratio',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'u64', '0x2::clock::Clock'],
            ['self', 'AdminCap', 'pool', 'minOpenRiskRatio']),
      );
}

/// Create a PoolConfig with margin pool IDs and risk parameters Enable is false by
/// default, must be enabled after registration
MoveCallBuilder newPoolConfig(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::new_pool_config',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          'u64',
          'u64',
          'u64',
          'u64',
          'u64',
          'u64'
        ], [
          'self',
          'minWithdrawRiskRatio',
          'minBorrowRiskRatio',
          'liquidationRiskRatio',
          'targetLiquidationRiskRatio',
          'userLiquidationReward',
          'poolLiquidationReward'
        ]),
      );
}

/// Create a PoolConfig with default risk parameters based on leverage
MoveCallBuilder newPoolConfigWithLeverage(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::new_pool_config_with_leverage',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, 'u64'], ['self', 'leverage']),
      );
}

/// Check if a deepbook pool is registered for margin trading
MoveCallBuilder poolEnabled(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::pool_enabled',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'pool']),
      );
}

/// Get the margin pool id for the given asset.
MoveCallBuilder getMarginPoolId(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::get_margin_pool_id',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Get the margin pool IDs for a deepbook pool
MoveCallBuilder getDeepbookPoolMarginPoolIds(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::get_deepbook_pool_margin_pool_ids',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, '0x2::object::ID'], ['self', 'deepbookPoolId']),
      );
}

/// Get the margin manager IDs for a given owner
MoveCallBuilder getMarginManagerIds(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::get_margin_manager_ids',
        arguments: normalizeMoveArguments(
            tx, arguments, [null, 'address'], ['self', 'owner']),
      );
}

MoveCallBuilder canLiquidate({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::can_liquidate',
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, '0x2::object::ID', 'u64'],
            ['self', 'deepbookPoolId', 'riskRatio']),
      );
}

MoveCallBuilder baseMarginPoolId(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::base_margin_pool_id',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, '0x2::object::ID'], ['self', 'deepbookPoolId']),
      );
}

MoveCallBuilder quoteMarginPoolId(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::quote_margin_pool_id',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, '0x2::object::ID'], ['self', 'deepbookPoolId']),
      );
}

MoveCallBuilder minWithdrawRiskRatio(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::min_withdraw_risk_ratio',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, '0x2::object::ID'], ['self', 'deepbookPoolId']),
      );
}

MoveCallBuilder minBorrowRiskRatio(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::min_borrow_risk_ratio',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, '0x2::object::ID'], ['self', 'deepbookPoolId']),
      );
}

MoveCallBuilder liquidationRiskRatio(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::liquidation_risk_ratio',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, '0x2::object::ID'], ['self', 'deepbookPoolId']),
      );
}

MoveCallBuilder targetLiquidationRiskRatio(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::target_liquidation_risk_ratio',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, '0x2::object::ID'], ['self', 'deepbookPoolId']),
      );
}

/// Post-trade solvency floor for _opening_ (risk-increasing) orders, sitting in
/// `(liquidation_risk_ratio, min_borrow_risk_ratio]`. Lets a max-leverage open
/// absorb the opening trade's spread — which lands the post-trade ratio just under
/// the borrow floor — without aborting, while staying above the liquidatable zone.
/// Defaults to the midpoint of liquidation and min_borrow; an admin override
/// (`set_min_open_risk_ratio`) is honored only while it stays in the valid band, so
/// a later risk-param change can't strand it below liquidation.
MoveCallBuilder minOpenRiskRatio(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::min_open_risk_ratio',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, '0x2::object::ID'], ['self', 'deepbookPoolId']),
      );
}

MoveCallBuilder userLiquidationReward(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::user_liquidation_reward',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, '0x2::object::ID'], ['self', 'deepbookPoolId']),
      );
}

MoveCallBuilder poolLiquidationReward(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::pool_liquidation_reward',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, '0x2::object::ID'], ['self', 'deepbookPoolId']),
      );
}

MoveCallBuilder allowedMaintainers(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::allowed_maintainers',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder allowedPauseCaps(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::allowed_pause_caps',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Get the pool configuration for a deepbook pool
MoveCallBuilder getPoolConfig({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_registry::get_pool_config',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, '0x2::object::ID'], ['self', 'deepbookPoolId']),
      );
}
