// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/sui/balance.dart' as balance;
import './margin_state.dart' as margin_state;
import './protocol_config.dart' as protocol_config;
import './protocol_fees.dart' as protocol_fees;
import './position_manager.dart' as position_manager;
import './deps/sui/vec_set.dart' as vec_set;
import './rate_limiter.dart' as rate_limiter;
import './deps/sui/vec_map.dart' as vec_map;
import './deps/std/type_name.dart' as type_name;

const $moduleName = '@deepbook/margin::margin_pool';

final MarginPool = Bcs.struct('${$moduleName}::MarginPool<phantom Asset>', {
  'id': SuiBcs.Address,
  'vault': balance.Balance,
  'state': margin_state.State,
  'config': protocol_config.ProtocolConfig,
  'protocol_fees': protocol_fees.ProtocolFees,
  'positions': position_manager.PositionManager,
  'allowed_deepbook_pools': vec_set.VecSet(SuiBcs.Address),
  'rate_limiter': rate_limiter.RateLimiter,
  'extra_fields': vec_map.VecMap(SuiBcs.STRING, SuiBcs.U64),
});

final SupplierCap = Bcs.struct('${$moduleName}::SupplierCap', {
  'id': SuiBcs.Address,
});

final MarginPoolCreated = Bcs.struct('${$moduleName}::MarginPoolCreated', {
  'margin_pool_id': SuiBcs.Address,
  'maintainer_cap_id': SuiBcs.Address,
  'asset_type': type_name.TypeName,
  'config': protocol_config.ProtocolConfig,
  'timestamp': SuiBcs.U64,
});

final MaintainerFeesWithdrawn =
    Bcs.struct('${$moduleName}::MaintainerFeesWithdrawn', {
  'margin_pool_id': SuiBcs.Address,
  'margin_pool_cap_id': SuiBcs.Address,
  'maintainer_fees': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

final ProtocolFeesWithdrawn =
    Bcs.struct('${$moduleName}::ProtocolFeesWithdrawn', {
  'margin_pool_id': SuiBcs.Address,
  'protocol_fees': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

final DeepbookPoolUpdated = Bcs.struct('${$moduleName}::DeepbookPoolUpdated', {
  'margin_pool_id': SuiBcs.Address,
  'deepbook_pool_id': SuiBcs.Address,
  'pool_cap_id': SuiBcs.Address,
  'enabled': SuiBcs.BOOL,
  'timestamp': SuiBcs.U64,
});

final InterestParamsUpdated =
    Bcs.struct('${$moduleName}::InterestParamsUpdated', {
  'margin_pool_id': SuiBcs.Address,
  'pool_cap_id': SuiBcs.Address,
  'interest_config': protocol_config.InterestConfig,
  'timestamp': SuiBcs.U64,
});

final MarginPoolConfigUpdated =
    Bcs.struct('${$moduleName}::MarginPoolConfigUpdated', {
  'margin_pool_id': SuiBcs.Address,
  'pool_cap_id': SuiBcs.Address,
  'margin_pool_config': protocol_config.MarginPoolConfig,
  'timestamp': SuiBcs.U64,
});

final AssetSupplied = Bcs.struct('${$moduleName}::AssetSupplied', {
  'margin_pool_id': SuiBcs.Address,
  'asset_type': type_name.TypeName,
  'supplier_cap_id': SuiBcs.Address,
  'supply_amount': SuiBcs.U64,
  'supply_shares': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

final AssetWithdrawn = Bcs.struct('${$moduleName}::AssetWithdrawn', {
  'margin_pool_id': SuiBcs.Address,
  'asset_type': type_name.TypeName,
  'supplier_cap_id': SuiBcs.Address,
  'withdraw_amount': SuiBcs.U64,
  'withdraw_shares': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

final SupplierCapMinted = Bcs.struct('${$moduleName}::SupplierCapMinted', {
  'supplier_cap_id': SuiBcs.Address,
  'timestamp': SuiBcs.U64,
});

final SupplyReferralMinted =
    Bcs.struct('${$moduleName}::SupplyReferralMinted', {
  'margin_pool_id': SuiBcs.Address,
  'supply_referral_id': SuiBcs.Address,
  'owner': SuiBcs.Address,
  'timestamp': SuiBcs.U64,
});

/// Creates and registers a new margin pool. If a same asset pool already exists,
/// abort. Sends a `MarginPoolCap` to the pool creator. Returns the created margin
/// pool id.
MoveCallBuilder createMarginPool(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::create_margin_pool',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, '0x2::clock::Clock'],
            ['registry', 'config', 'maintainerCap']),
      );
}

/// Allow a margin manager tied to a deepbook pool to borrow from the margin pool.
MoveCallBuilder enableDeepbookPoolForLoan(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::enable_deepbook_pool_for_loan',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, '0x2::object::ID', null, '0x2::clock::Clock'],
            ['self', 'registry', 'deepbookPoolId', 'marginPoolCap']),
      );
}

/// Disable a margin manager tied to a deepbook pool from borrowing from the margin
/// pool.
MoveCallBuilder disableDeepbookPoolForLoan(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::disable_deepbook_pool_for_loan',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, '0x2::object::ID', null, '0x2::clock::Clock'],
            ['self', 'registry', 'deepbookPoolId', 'marginPoolCap']),
      );
}

/// Updates interest params for the margin pool
MoveCallBuilder updateInterestParams(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::update_interest_params',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, null, '0x2::clock::Clock'],
            ['self', 'registry', 'interestConfig', 'marginPoolCap']),
      );
}

/// Updates margin pool config
MoveCallBuilder updateMarginPoolConfig(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::update_margin_pool_config',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, null, '0x2::clock::Clock'],
            ['self', 'registry', 'marginPoolConfig', 'marginPoolCap']),
      );
}

/// Inject capital into the margin pool without minting supplier shares.
MoveCallBuilder adminInjectCapital(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::admin_inject_capital',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, '0x2::clock::Clock'],
            ['self', 'AdminCap', 'coin']),
      );
}

/// Mint a new SupplierCap, which is used to supply and withdraw from margin pools.
/// One SupplierCap can be used to supply and withdraw from multiple margin pools.
MoveCallBuilder mintSupplierCap({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::mint_supplier_cap',
        arguments: normalizeMoveArguments(
            tx, arguments, [null, '0x2::clock::Clock'], ['registry']),
      );
}

/// Supply to the margin pool using a SupplierCap. Returns the new supply shares.
/// The `referral` parameter should be the ID of a SupplyReferral object if referral
/// tracking is desired.
MoveCallBuilder supply(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::supply',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          '0x1::option::Option<0x2::object::ID>',
          '0x2::clock::Clock'
        ], [
          'self',
          'registry',
          'supplierCap',
          'coin',
          'referral'
        ]),
      );
}

/// Withdraw from the margin pool using a SupplierCap. Returns the withdrawn coin.
MoveCallBuilder withdraw(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::withdraw',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, '0x1::option::Option<u64>', '0x2::clock::Clock'],
            ['self', 'registry', 'supplierCap', 'amount']),
      );
}

/// Mint a supply referral.
MoveCallBuilder mintSupplyReferral(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::mint_supply_referral',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments,
            [null, null, '0x2::clock::Clock'], ['self', 'registry']),
      );
}

/// Withdraw the referral fees.
MoveCallBuilder withdrawReferralFees(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::withdraw_referral_fees',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, null],
            ['self', 'registry', 'referral']),
      );
}

/// Withdraw the default referral fees (admin only). The default referral at 0x0
/// doesn't have a SupplyReferral object,
MoveCallBuilder adminWithdrawDefaultReferralFees(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::admin_withdraw_default_referral_fees',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, null],
            ['self', 'registry', 'AdminCap']),
      );
}

/// Withdraw the maintainer fees. The `margin_pool_cap` parameter is used to ensure
/// the correct margin pool is being withdrawn from.
MoveCallBuilder withdrawMaintainerFees(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::withdraw_maintainer_fees',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, '0x2::clock::Clock'],
            ['self', 'registry', 'marginPoolCap']),
      );
}

/// Withdraw the protocol fees.
MoveCallBuilder withdrawProtocolFees(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::withdraw_protocol_fees',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, '0x2::clock::Clock'],
            ['self', 'registry', 'AdminCap']),
      );
}

/// Return the ID of the margin pool.
MoveCallBuilder id(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::id',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Return whether a margin manager for a given deepbook pool is allowed to borrow
/// from the margin pool.
MoveCallBuilder deepbookPoolAllowed(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::deepbook_pool_allowed',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments,
            [null, '0x2::object::ID'], ['self', 'deepbookPoolId']),
      );
}

/// Return the current total supply of the margin pool.
MoveCallBuilder totalSupply(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::total_supply',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Return the current total supply of the margin pool including accrued interest.
MoveCallBuilder totalSupplyWithInterest(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::total_supply_with_interest',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, '0x2::clock::Clock'], ['self']),
      );
}

/// Return the current total supply shares of the margin pool.
MoveCallBuilder supplyShares(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::supply_shares',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Return the current supply ratio of the margin pool.
MoveCallBuilder supplyRatio(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::supply_ratio',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Return the current total borrow of the margin pool.
MoveCallBuilder totalBorrow(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::total_borrow',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Return the current total borrow shares of the margin pool.
MoveCallBuilder borrowShares(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::borrow_shares',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Return the current borrow ratio of the margin pool.
MoveCallBuilder borrowRatio(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::borrow_ratio',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Return the last update timestamp of the margin pool.
MoveCallBuilder lastUpdateTimestamp(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::last_update_timestamp',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Return the supply cap of the margin pool.
MoveCallBuilder supplyCap(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::supply_cap',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Return the current protocol fees of the margin pool.
MoveCallBuilder protocolFees(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::protocol_fees',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Return the current max utilization rate of the margin pool.
MoveCallBuilder maxUtilizationRate(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::max_utilization_rate',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Return the current protocol spread of the margin pool.
MoveCallBuilder protocolSpread(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::protocol_spread',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Return the current min borrow of the margin pool.
MoveCallBuilder minBorrow(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::min_borrow',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Return the current interest rate of the margin pool. Represented in 9 decimal
/// places.
MoveCallBuilder interestRate(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::interest_rate',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder trueInterestRate(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::true_interest_rate',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Return the current user supply shares of the margin pool.
MoveCallBuilder userSupplyShares(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::user_supply_shares',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments,
            [null, '0x2::object::ID'], ['self', 'supplierCapId']),
      );
}

/// Return the current vault balance of the margin pool.
MoveCallBuilder vaultBalance(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::vault_balance',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Return the current user supply amount of the margin pool.
MoveCallBuilder userSupplyAmount(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::user_supply_amount',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, '0x2::object::ID', '0x2::clock::Clock'],
            ['self', 'supplierCapId']),
      );
}

/// Returns the maximum amount that can be withdrawn without hitting rate limits
MoveCallBuilder getAvailableWithdrawal(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::get_available_withdrawal',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, '0x2::clock::Clock'], ['self']),
      );
}

/// Returns whether rate limiting is enabled
MoveCallBuilder isRateLimitEnabled(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::is_rate_limit_enabled',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Returns the rate limit capacity (max bucket size)
MoveCallBuilder rateLimitCapacity(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::rate_limit_capacity',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Returns the rate limit refill rate per millisecond
MoveCallBuilder rateLimitRefillRatePerMs(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::margin_pool::rate_limit_refill_rate_per_ms',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}
