// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/sui/vec_map.dart' as vec_map;

const $moduleName = '@deepbook/margin::margin_state';

final State = Bcs.struct('${$moduleName}::State', {
  'total_supply': SuiBcs.U64,
  'total_borrow': SuiBcs.U64,
  'supply_shares': SuiBcs.U64,
  'borrow_shares': SuiBcs.U64,
  'last_update_timestamp': SuiBcs.U64,
  'extra_fields': vec_map.VecMap(SuiBcs.STRING, SuiBcs.U64),
});
