// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/std/type_name.dart' as type_name;
import './deps/sui/vec_map.dart' as vec_map;

const $moduleName = '@deepbook/margin::oracle';

final CoinTypeData = Bcs.struct('${$moduleName}::CoinTypeData', {
  'decimals': SuiBcs.U8,
  'price_feed_id': Bcs.vector(SuiBcs.U8),
  'type_name': type_name.TypeName,
  'max_conf_bps': SuiBcs.U64,
  'max_ewma_difference_bps': SuiBcs.U64,
});

final PythConfig = Bcs.struct('${$moduleName}::PythConfig', {
  'currencies': vec_map.VecMap(type_name.TypeName, CoinTypeData),
  'max_age_secs': SuiBcs.U64,
});

final ConversionConfig = Bcs.struct('${$moduleName}::ConversionConfig', {
  'target_decimals': SuiBcs.U8,
  'base_decimals': SuiBcs.U8,
  'pyth_price': SuiBcs.U64,
  'pyth_decimals': SuiBcs.U8,
});

/// Creates a new CoinTypeData struct of type T. Uses Currency to avoid any errors
/// in decimals.
MoveCallBuilder newCoinTypeDataFromCurrency(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::oracle::new_coin_type_data_from_currency',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, 'vector<u8>', 'u64', 'u64'],
            ['currency', 'priceFeedId', 'maxConfBps', 'maxEwmaDifferenceBps']),
      );
}

/// Creates a new PythConfig struct. Can be attached by the Admin to MarginRegistry
/// to allow oracle to work.
MoveCallBuilder newPythConfig({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::oracle::new_pyth_config',
        arguments: normalizeMoveArguments(
            tx, arguments, ['vector<null>', 'u64'], ['setups', 'maxAgeSecs']),
      );
}
