// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';

/// Updates the current price for a pool using safe oracle price calculation. Anyone
/// can call this to update the price oracle used for order validation.
MoveCallBuilder updateCurrentPrice(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::update_current_price',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          '0x2::clock::Clock'
        ], [
          'registry',
          'pool',
          'basePriceInfoObject',
          'quotePriceInfoObject'
        ]),
      );
}

/// DEPRECATED. Use `place_limit_order_v2`.
MoveCallBuilder placeLimitOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::place_limit_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          'u64',
          'u8',
          'u8',
          'u64',
          'u64',
          'bool',
          'bool',
          'u64',
          '0x2::clock::Clock'
        ], [
          'Registry',
          'MarginManager',
          'Pool',
          'ClientOrderId',
          'OrderType',
          'SelfMatchingOption',
          'Price',
          'Quantity',
          'IsBid',
          'PayWithDeep',
          'ExpireTimestamp'
        ]),
      );
}

/// DEPRECATED. Use `place_market_order_v2`.
MoveCallBuilder placeMarketOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::place_market_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          'u64',
          'u8',
          'u64',
          'bool',
          'bool',
          '0x2::clock::Clock'
        ], [
          'Registry',
          'MarginManager',
          'Pool',
          'ClientOrderId',
          'SelfMatchingOption',
          'Quantity',
          'IsBid',
          'PayWithDeep'
        ]),
      );
}

/// DEPRECATED. Use `place_reduce_only_limit_order_v2`.
MoveCallBuilder placeReduceOnlyLimitOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::place_reduce_only_limit_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          'u64',
          'u8',
          'u8',
          'u64',
          'u64',
          'bool',
          'bool',
          'u64',
          '0x2::clock::Clock'
        ], [
          'Registry',
          'MarginManager',
          'Pool',
          'MarginPool',
          'ClientOrderId',
          'OrderType',
          'SelfMatchingOption',
          'Price',
          'Quantity',
          'IsBid',
          'PayWithDeep',
          'ExpireTimestamp'
        ]),
      );
}

/// DEPRECATED. Use `place_reduce_only_market_order_v2`.
MoveCallBuilder placeReduceOnlyMarketOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::place_reduce_only_market_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          'u64',
          'u8',
          'u64',
          'bool',
          'bool',
          '0x2::clock::Clock'
        ], [
          'Registry',
          'MarginManager',
          'Pool',
          'MarginPool',
          'ClientOrderId',
          'SelfMatchingOption',
          'Quantity',
          'IsBid',
          'PayWithDeep'
        ]),
      );
}

/// Places a limit order in the pool.
MoveCallBuilder placeLimitOrderV2(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::place_limit_order_v2',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          'u64',
          'u8',
          'u8',
          'u64',
          'u64',
          'bool',
          'bool',
          'u64',
          '0x2::clock::Clock'
        ], [
          'registry',
          'marginManager',
          'pool',
          'baseMarginPool',
          'quoteMarginPool',
          'baseOracle',
          'quoteOracle',
          'clientOrderId',
          'orderType',
          'selfMatchingOption',
          'price',
          'quantity',
          'isBid',
          'payWithDeep',
          'expireTimestamp'
        ]),
      );
}

/// Places a market order in the pool.
MoveCallBuilder placeMarketOrderV2(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::place_market_order_v2',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          'u64',
          'u8',
          'u64',
          'bool',
          'bool',
          '0x2::clock::Clock'
        ], [
          'registry',
          'marginManager',
          'pool',
          'baseMarginPool',
          'quoteMarginPool',
          'baseOracle',
          'quoteOracle',
          'clientOrderId',
          'selfMatchingOption',
          'quantity',
          'isBid',
          'payWithDeep'
        ]),
      );
}

/// Places a reduce-only order in the pool. Used when margin trading is disabled.
MoveCallBuilder placeReduceOnlyLimitOrderV2(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::place_reduce_only_limit_order_v2',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          'u64',
          'u8',
          'u8',
          'u64',
          'u64',
          'bool',
          'bool',
          'u64',
          '0x2::clock::Clock'
        ], [
          'registry',
          'marginManager',
          'pool',
          'baseMarginPool',
          'quoteMarginPool',
          'baseOracle',
          'quoteOracle',
          'clientOrderId',
          'orderType',
          'selfMatchingOption',
          'price',
          'quantity',
          'isBid',
          'payWithDeep',
          'expireTimestamp'
        ]),
      );
}

/// Places a reduce-only market order in the pool. Used when margin trading is
/// disabled.
///
/// Superseded by `place_reduce_only_market_order_and_repay_loan`. A market (taker)
/// fill always pays the spread, which lowers the oracle-valued `risk_ratio` while
/// the debt is unchanged, so the swap-only monotonic check here rejects essentially
/// every taker fill. The `_and_repay` variant deleverages with the proceeds so the
/// net-state ratio actually improves. Kept callable for existing integrators; its
/// reduce-only _direction_ guard matches the other entries — a bid needs base
/// (short-side) debt, the ask needs quote (long-side) debt and sells up to gross
/// base held — with no size cap.
MoveCallBuilder placeReduceOnlyMarketOrderV2(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::place_reduce_only_market_order_v2',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          'u64',
          'u8',
          'u64',
          'bool',
          'bool',
          '0x2::clock::Clock'
        ], [
          'registry',
          'marginManager',
          'pool',
          'baseMarginPool',
          'quoteMarginPool',
          'baseOracle',
          'quoteOracle',
          'clientOrderId',
          'selfMatchingOption',
          'quantity',
          'isBid',
          'payWithDeep'
        ]),
      );
}

/// Atomically winds down a leveraged position: places a reduce-only market order,
/// repays the loan with the proceeds, then requires the net (post-repay) risk ratio
/// to be at least the pre-trade ratio.
///
/// The post-repay check is the point. A market close pays the spread, which alone
/// lowers the oracle-valued ratio (debt is unchanged until repay) and would abort
/// the plain reduce-only path. Repaying first deleverages and absorbs the slippage
/// (still bounded by the `assert_price` band), and lets a manager in the
/// `liquidation..min_borrow` band climb out — it cannot reach the borrow floor in a
/// single swap.
MoveCallBuilder placeReduceOnlyMarketOrderAndRepayLoan(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::place_reduce_only_market_order_and_repay_loan',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          'u64',
          'u8',
          'u64',
          'bool',
          'bool',
          '0x2::clock::Clock'
        ], [
          'registry',
          'marginManager',
          'pool',
          'baseMarginPool',
          'quoteMarginPool',
          'baseOracle',
          'quoteOracle',
          'clientOrderId',
          'selfMatchingOption',
          'quantity',
          'isBid',
          'payWithDeep'
        ]),
      );
}

/// Reduce-only **limit** order that atomically repays the loan with the taker
/// fills. It is the limit/maker behaviour of `place_reduce_only_limit_order_v2`
/// plus the repay-then-net-monotonic gate of
/// `place_reduce_only_market_order_and_repay_loan`: the portion that crosses the
/// book fills immediately and settles, the rest rests as a maker, then the settled
/// (taker) proceeds repay the debt before the monotonic check on the net
/// (post-repay) state.
///
/// This is the danger-band tool for a _price-bounded_ reduce: a crossing
/// reduce-only limit pays the spread on its taker fills, which alone would abort
/// `place_reduce_only_limit_order_v2`'s swap-only monotonic check; repaying first
/// deleverages so the net ratio holds. The resting remainder only locks balance
/// (counted in assets), so it doesn't move the ratio. Unfilled-and-resting behaves
/// exactly like `place_reduce_only_limit_order_v2` (nothing to repay).
MoveCallBuilder placeReduceOnlyLimitOrderAndRepayLoan(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::place_reduce_only_limit_order_and_repay_loan',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          'u64',
          'u8',
          'u8',
          'u64',
          'u64',
          'bool',
          'bool',
          'u64',
          '0x2::clock::Clock'
        ], [
          'registry',
          'marginManager',
          'pool',
          'baseMarginPool',
          'quoteMarginPool',
          'baseOracle',
          'quoteOracle',
          'clientOrderId',
          'orderType',
          'selfMatchingOption',
          'price',
          'quantity',
          'isBid',
          'payWithDeep',
          'expireTimestamp'
        ]),
      );
}

/// Atomically places a market order and repays the loan with the proceeds, gating
/// on a **monotonic** net-state check: if any debt remains after the repay, the
/// post-repay `risk_ratio` must be at least the pre-trade ratio (improve-or-hold).
/// A full close drives debt to 0 (`risk_ratio` MAX), which always passes.
///
/// This is the everyday close / deleverage tool. The monotonic gate — rather than
/// the `min_open` opening floor used by `place_market_order_v2` — lets a position
/// in the `liquidation..min_borrow` danger band wind down _partially_: a small
/// close that lifts the ratio from, say, 1.12 to 1.15 is allowed even though 1.15
/// is still below `min_open`, which the opening floor would reject.
///
/// Not reduce-only and uncapped, but the monotonic check makes a quantity cap
/// unnecessary: a market (taker) fill settles immediately, so any genuinely
/// exposure-_increasing_ trade lowers the ratio and aborts here, while any
/// deleveraging trade is allowed at any size — an overshoot past the debt is fine
/// (surplus is the manager's own holding) and `assert_price` still bounds slippage.
/// Requires margin trading enabled; in reduce-only mode use
/// `place_reduce_only_market_order_and_repay_loan`.
MoveCallBuilder placeMarketOrderAndRepayLoan(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::place_market_order_and_repay_loan',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          'u64',
          'u8',
          'u64',
          'bool',
          'bool',
          '0x2::clock::Clock'
        ], [
          'registry',
          'marginManager',
          'pool',
          'baseMarginPool',
          'quoteMarginPool',
          'baseOracle',
          'quoteOracle',
          'clientOrderId',
          'selfMatchingOption',
          'quantity',
          'isBid',
          'payWithDeep'
        ]),
      );
}

/// Modifies an order
MoveCallBuilder modifyOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::modify_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'u128', 'u64', '0x2::clock::Clock'],
            ['registry', 'marginManager', 'pool', 'orderId', 'newQuantity']),
      );
}

/// Cancels an order
MoveCallBuilder cancelOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::cancel_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'u128', '0x2::clock::Clock'],
            ['registry', 'marginManager', 'pool', 'orderId']),
      );
}

/// Cancel multiple orders within a vector.
MoveCallBuilder cancelOrders(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::cancel_orders',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'vector<u128>', '0x2::clock::Clock'],
            ['registry', 'marginManager', 'pool', 'orderIds']),
      );
}

/// Cancels all orders for the given account.
MoveCallBuilder cancelAllOrders(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::cancel_all_orders',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, '0x2::clock::Clock'],
            ['registry', 'marginManager', 'pool']),
      );
}

/// Withdraw settled amounts to balance_manager.
MoveCallBuilder withdrawSettledAmounts(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::withdraw_settled_amounts',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, null],
            ['registry', 'marginManager', 'pool']),
      );
}

/// Withdraw settled amounts to balance_manager permissionlessly. Anyone can call
/// this function to settle balances for a margin manager.
MoveCallBuilder withdrawSettledAmountsPermissionless(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::withdraw_settled_amounts_permissionless',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, null],
            ['registry', 'marginManager', 'pool']),
      );
}

/// Stake DEEP tokens to the pool.
MoveCallBuilder stake(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::stake',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'u64'],
            ['registry', 'marginManager', 'pool', 'amount']),
      );
}

/// Unstake DEEP tokens from the pool.
MoveCallBuilder unstake(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::unstake',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, null],
            ['registry', 'marginManager', 'pool']),
      );
}

/// Submit proposal using the margin manager.
MoveCallBuilder submitProposal(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::submit_proposal',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          'u64',
          'u64',
          'u64'
        ], [
          'registry',
          'marginManager',
          'pool',
          'takerFee',
          'makerFee',
          'stakeRequired'
        ]),
      );
}

/// Vote on a proposal using the margin manager.
MoveCallBuilder vote(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::vote',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, '0x2::object::ID'],
            ['registry', 'marginManager', 'pool', 'proposalId']),
      );
}

MoveCallBuilder claimRebates(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::pool_proxy::claim_rebates',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, null],
            ['registry', 'marginManager', 'pool']),
      );
}
