// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/sui/table.dart' as table;
import './deps/sui/vec_map.dart' as vec_map;

const $moduleName = '@deepbook/margin::protocol_fees';

final ProtocolFees = Bcs.struct('${$moduleName}::ProtocolFees', {
  'referrals': table.Table,
  'total_shares': SuiBcs.U64,
  'fees_per_share': SuiBcs.U64,
  'maintainer_fees': SuiBcs.U64,
  'protocol_fees': SuiBcs.U64,
  'extra_fields': vec_map.VecMap(SuiBcs.STRING, SuiBcs.U64),
});

final ReferralTracker = Bcs.struct('${$moduleName}::ReferralTracker', {
  'current_shares': SuiBcs.U64,
  'last_fees_per_share': SuiBcs.U64,
  'unclaimed_fees': SuiBcs.U64,
});

final SupplyReferral = Bcs.struct('${$moduleName}::SupplyReferral', {
  'id': SuiBcs.Address,
  'owner': SuiBcs.Address,
});

final ProtocolFeesIncreasedEvent =
    Bcs.struct('${$moduleName}::ProtocolFeesIncreasedEvent', {
  'margin_pool_id': SuiBcs.Address,
  'total_shares': SuiBcs.U64,
  'referral_fees': SuiBcs.U64,
  'maintainer_fees': SuiBcs.U64,
  'protocol_fees': SuiBcs.U64,
});

final ReferralFeesClaimedEvent =
    Bcs.struct('${$moduleName}::ReferralFeesClaimedEvent', {
  'referral_id': SuiBcs.Address,
  'owner': SuiBcs.Address,
  'fees': SuiBcs.U64,
});

/// Get the maintainer fees.
MoveCallBuilder maintainerFees({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::protocol_fees::maintainer_fees',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Get the protocol fees.
MoveCallBuilder protocolFees({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::protocol_fees::protocol_fees',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder referralTracker({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::protocol_fees::referral_tracker',
        arguments: normalizeMoveArguments(
            tx, arguments, [null, '0x2::object::ID'], ['self', 'referral']),
      );
}

MoveCallBuilder totalShares({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::protocol_fees::total_shares',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder feesPerShare({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::protocol_fees::fees_per_share',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}
