// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/sui/vec_map.dart' as vec_map;

const $moduleName = '@deepbook/margin::protocol_config';

final MarginPoolConfig = Bcs.struct('${$moduleName}::MarginPoolConfig', {
  'supply_cap': SuiBcs.U64,
  'max_utilization_rate': SuiBcs.U64,
  'protocol_spread': SuiBcs.U64,
  'min_borrow': SuiBcs.U64,
  'rate_limit_capacity': SuiBcs.U64,
  'rate_limit_refill_rate_per_ms': SuiBcs.U64,
  'rate_limit_enabled': SuiBcs.BOOL,
});

final InterestConfig = Bcs.struct('${$moduleName}::InterestConfig', {
  'base_rate': SuiBcs.U64,
  'base_slope': SuiBcs.U64,
  'optimal_utilization': SuiBcs.U64,
  'excess_slope': SuiBcs.U64,
});

final ProtocolConfig = Bcs.struct('${$moduleName}::ProtocolConfig', {
  'margin_pool_config': MarginPoolConfig,
  'interest_config': InterestConfig,
  'extra_fields': vec_map.VecMap(SuiBcs.STRING, SuiBcs.U64),
});

MoveCallBuilder newProtocolConfig(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::protocol_config::new_protocol_config',
        arguments: normalizeMoveArguments(tx, arguments, [null, null],
            ['marginPoolConfig', 'interestConfig']),
      );
}

MoveCallBuilder newMarginPoolConfig(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::protocol_config::new_margin_pool_config',
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            ['u64', 'u64', 'u64', 'u64'],
            ['supplyCap', 'maxUtilizationRate', 'protocolSpread', 'minBorrow']),
      );
}

MoveCallBuilder newMarginPoolConfigWithRateLimit(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::protocol_config::new_margin_pool_config_with_rate_limit',
        arguments: normalizeMoveArguments(tx, arguments, [
          'u64',
          'u64',
          'u64',
          'u64',
          'u64',
          'u64',
          'bool'
        ], [
          'supplyCap',
          'maxUtilizationRate',
          'protocolSpread',
          'minBorrow',
          'rateLimitCapacity',
          'rateLimitRefillRatePerMs',
          'rateLimitEnabled'
        ]),
      );
}

MoveCallBuilder newInterestConfig(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::protocol_config::new_interest_config',
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            ['u64', 'u64', 'u64', 'u64'],
            ['baseRate', 'baseSlope', 'optimalUtilization', 'excessSlope']),
      );
}
