// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';

const $moduleName = '@deepbook/margin::rate_limiter';

final RateLimiter = Bcs.struct('${$moduleName}::RateLimiter', {
  'available': SuiBcs.U64,
  'last_updated_ms': SuiBcs.U64,
  'capacity': SuiBcs.U64,
  'refill_rate_per_ms': SuiBcs.U64,
  'enabled': SuiBcs.BOOL,
});

MoveCallBuilder isEnabled({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::rate_limiter::is_enabled',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder capacity({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::rate_limiter::capacity',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder refillRatePerMs({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::rate_limiter::refill_rate_per_ms',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}
