// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';

const $moduleName = '@deepbook/margin::tpsl';

final Condition = Bcs.struct('${$moduleName}::Condition', {
  'trigger_below_price': SuiBcs.BOOL,
  'trigger_price': SuiBcs.U64,
});

final PendingOrder = Bcs.struct('${$moduleName}::PendingOrder', {
  'is_limit_order': SuiBcs.BOOL,
  'client_order_id': SuiBcs.U64,
  'order_type': Bcs.option(SuiBcs.U8),
  'self_matching_option': SuiBcs.U8,
  'price': Bcs.option(SuiBcs.U64),
  'quantity': SuiBcs.U64,
  'is_bid': SuiBcs.BOOL,
  'pay_with_deep': SuiBcs.BOOL,
  'expire_timestamp': Bcs.option(SuiBcs.U64),
});

final ConditionalOrder = Bcs.struct('${$moduleName}::ConditionalOrder', {
  'conditional_order_id': SuiBcs.U64,
  'condition': Condition,
  'pending_order': PendingOrder,
});

final TakeProfitStopLoss = Bcs.struct('${$moduleName}::TakeProfitStopLoss', {
  'trigger_below': Bcs.vector(ConditionalOrder),
  'trigger_above': Bcs.vector(ConditionalOrder),
});

final ConditionalOrderAdded =
    Bcs.struct('${$moduleName}::ConditionalOrderAdded', {
  'manager_id': SuiBcs.Address,
  'conditional_order_id': SuiBcs.U64,
  'conditional_order': ConditionalOrder,
  'timestamp': SuiBcs.U64,
});

final ConditionalOrderCancelled =
    Bcs.struct('${$moduleName}::ConditionalOrderCancelled', {
  'manager_id': SuiBcs.Address,
  'conditional_order_id': SuiBcs.U64,
  'conditional_order': ConditionalOrder,
  'timestamp': SuiBcs.U64,
});

final ConditionalOrderExecuted =
    Bcs.struct('${$moduleName}::ConditionalOrderExecuted', {
  'manager_id': SuiBcs.Address,
  'pool_id': SuiBcs.Address,
  'conditional_order_id': SuiBcs.U64,
  'conditional_order': ConditionalOrder,
  'timestamp': SuiBcs.U64,
});

final ConditionalOrderInsufficientFunds =
    Bcs.struct('${$moduleName}::ConditionalOrderInsufficientFunds', {
  'manager_id': SuiBcs.Address,
  'conditional_order_id': SuiBcs.U64,
  'conditional_order': ConditionalOrder,
  'timestamp': SuiBcs.U64,
});

final ConditionalOrderPriceOutOfBounds =
    Bcs.struct('${$moduleName}::ConditionalOrderPriceOutOfBounds', {
  'manager_id': SuiBcs.Address,
  'conditional_order_id': SuiBcs.U64,
  'conditional_order': ConditionalOrder,
  'timestamp': SuiBcs.U64,
});

final ConditionalOrderBelowLiquidation =
    Bcs.struct('${$moduleName}::ConditionalOrderBelowLiquidation', {
  'manager_id': SuiBcs.Address,
  'conditional_order_id': SuiBcs.U64,
  'conditional_order': ConditionalOrder,
  'timestamp': SuiBcs.U64,
});

MoveCallBuilder newCondition({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::new_condition',
        arguments: normalizeMoveArguments(tx, arguments, ['bool', 'u64'],
            ['triggerBelowPrice', 'triggerPrice']),
      );
}

/// Creates a new pending limit order. Order type must be no restriction or
/// immediate or cancel.
MoveCallBuilder newPendingLimitOrder(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::new_pending_limit_order',
        arguments: normalizeMoveArguments(tx, arguments, [
          'u64',
          'u8',
          'u8',
          'u64',
          'u64',
          'bool',
          'bool',
          'u64'
        ], [
          'clientOrderId',
          'orderType',
          'selfMatchingOption',
          'price',
          'quantity',
          'isBid',
          'payWithDeep',
          'expireTimestamp'
        ]),
      );
}

/// Creates a new pending market order.
MoveCallBuilder newPendingMarketOrder(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::new_pending_market_order',
        arguments: normalizeMoveArguments(tx, arguments, [
          'u64',
          'u8',
          'u64',
          'bool',
          'bool'
        ], [
          'clientOrderId',
          'selfMatchingOption',
          'quantity',
          'isBid',
          'payWithDeep'
        ]),
      );
}

MoveCallBuilder triggerBelowOrders(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::trigger_below_orders',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder triggerAboveOrders(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::trigger_above_orders',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder numConditionalOrders(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::num_conditional_orders',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder conditionalOrderId(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::conditional_order_id',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['conditionalOrder']),
      );
}

MoveCallBuilder getConditionalOrder(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::get_conditional_order',
        arguments: normalizeMoveArguments(
            tx, arguments, [null, 'u64'], ['self', 'conditionalOrderId']),
      );
}

MoveCallBuilder condition({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::condition',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['conditionalOrder']),
      );
}

MoveCallBuilder pendingOrder({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::pending_order',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['conditionalOrder']),
      );
}

MoveCallBuilder triggerBelowPrice(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::trigger_below_price',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['condition']),
      );
}

MoveCallBuilder triggerPrice({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::trigger_price',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['condition']),
      );
}

MoveCallBuilder clientOrderId({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::client_order_id',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['pendingOrder']),
      );
}

MoveCallBuilder orderType({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::order_type',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['pendingOrder']),
      );
}

MoveCallBuilder selfMatchingOption(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::self_matching_option',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['pendingOrder']),
      );
}

MoveCallBuilder price({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::price',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['pendingOrder']),
      );
}

MoveCallBuilder quantity({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::quantity',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['pendingOrder']),
      );
}

MoveCallBuilder isBid({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::is_bid',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['pendingOrder']),
      );
}

MoveCallBuilder payWithDeep({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::pay_with_deep',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['pendingOrder']),
      );
}

MoveCallBuilder expireTimestamp({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::expire_timestamp',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['pendingOrder']),
      );
}

MoveCallBuilder isLimitOrder({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin';
  return (tx) => tx.moveCall(
        '$packageAddress::tpsl::is_limit_order',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['pendingOrder']),
      );
}
