// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './external_address.dart' as external_address;
import './deps/0x0000000000000000000000000000000000000000000000000000000000000002/table.dart'
    as table;
import './consumed_vaas.dart' as consumed_vaas;
import './fee_collector.dart' as fee_collector;
import './deps/0x0000000000000000000000000000000000000000000000000000000000000002/package.dart'
    as package;

const $moduleName =
    '0xf47329f4344f3bf0f8e436e2f7b485466cff300f12a166563995d3888c296a94::state';

final State = Bcs.struct('${$moduleName}::State', {
  'id': SuiBcs.Address,
  'governance_chain': SuiBcs.U16,
  'governance_contract': external_address.ExternalAddress,
  'guardian_set_index': SuiBcs.U32,
  'guardian_sets': table.Table,
  'guardian_set_seconds_to_live': SuiBcs.U32,
  'consumed_vaas': consumed_vaas.ConsumedVAAs,
  'fee_collector': fee_collector.FeeCollector,
  'upgrade_cap': package.UpgradeCap,
});
