// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/sui/bag.dart' as bag;

const $moduleName = '@deepbook/margin-liquidation::liquidation_vault';

final LIQUIDATION_VAULT = Bcs.struct('${$moduleName}::LIQUIDATION_VAULT', {
  'dummy_field': SuiBcs.BOOL,
});

final LiquidationVault = Bcs.struct('${$moduleName}::LiquidationVault', {
  'id': SuiBcs.Address,
  'vault': bag.Bag,
});

final BalanceKey = Bcs.struct('${$moduleName}::BalanceKey<phantom T>', {
  'dummy_field': SuiBcs.BOOL,
});

final AuthorizedTradersKey =
    Bcs.struct('${$moduleName}::AuthorizedTradersKey', {
  'dummy_field': SuiBcs.BOOL,
});

final LiquidationAdminCap = Bcs.struct('${$moduleName}::LiquidationAdminCap', {
  'id': SuiBcs.Address,
});

final LiquidationByVault = Bcs.struct('${$moduleName}::LiquidationByVault', {
  'vault_id': SuiBcs.Address,
  'margin_manager_id': SuiBcs.Address,
  'margin_pool_id': SuiBcs.Address,
  'base_in': SuiBcs.U64,
  'base_out': SuiBcs.U64,
  'quote_in': SuiBcs.U64,
  'quote_out': SuiBcs.U64,
  'repay_balance_remaining': SuiBcs.U64,
  'base_liquidation': SuiBcs.BOOL,
});

MoveCallBuilder deposit(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin-liquidation';
  return (tx) => tx.moveCall(
        '$packageAddress::liquidation_vault::deposit',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, null],
            ['self', 'LiquidationCap', 'coin']),
      );
}

MoveCallBuilder withdraw(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin-liquidation';
  return (tx) => tx.moveCall(
        '$packageAddress::liquidation_vault::withdraw',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, 'u64'],
            ['self', 'LiquidationCap', 'amount']),
      );
}

MoveCallBuilder createLiquidationVault(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin-liquidation';
  return (tx) => tx.moveCall(
        '$packageAddress::liquidation_vault::create_liquidation_vault',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['LiquidationCap']),
      );
}

MoveCallBuilder authorizeTrader({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin-liquidation';
  return (tx) => tx.moveCall(
        '$packageAddress::liquidation_vault::authorize_trader',
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, 'address'],
            ['self', 'LiquidationCap', 'authorizedAddress']),
      );
}

MoveCallBuilder deauthorizeTrader(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/margin-liquidation';
  return (tx) => tx.moveCall(
        '$packageAddress::liquidation_vault::deauthorize_trader',
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, 'address'],
            ['self', 'LiquidationCap', 'authorizedAddress']),
      );
}

MoveCallBuilder swapBaseToQuote(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin-liquidation';
  return (tx) => tx.moveCall(
        '$packageAddress::liquidation_vault::swap_base_to_quote',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, 'u64', 'u64', 'u64', '0x2::clock::Clock'],
            ['self', 'pool', 'baseIn', 'deepIn', 'minQuoteOut']),
      );
}

MoveCallBuilder swapQuoteToBase(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin-liquidation';
  return (tx) => tx.moveCall(
        '$packageAddress::liquidation_vault::swap_quote_to_base',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, 'u64', 'u64', 'u64', '0x2::clock::Clock'],
            ['self', 'pool', 'quoteIn', 'deepIn', 'minBaseOut']),
      );
}

MoveCallBuilder liquidateBase(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin-liquidation';
  return (tx) => tx.moveCall(
        '$packageAddress::liquidation_vault::liquidate_base',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          '0x1::option::Option<u64>',
          '0x2::clock::Clock'
        ], [
          'self',
          'marginManager',
          'registry',
          'baseOracle',
          'quoteOracle',
          'baseMarginPool',
          'quoteMarginPool',
          'pool',
          'repayAmount'
        ]),
      );
}

MoveCallBuilder liquidateQuote(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin-liquidation';
  return (tx) => tx.moveCall(
        '$packageAddress::liquidation_vault::liquidate_quote',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          '0x1::option::Option<u64>',
          '0x2::clock::Clock'
        ], [
          'self',
          'marginManager',
          'registry',
          'baseOracle',
          'quoteOracle',
          'baseMarginPool',
          'quoteMarginPool',
          'pool',
          'repayAmount'
        ]),
      );
}

MoveCallBuilder balance(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/margin-liquidation';
  return (tx) => tx.moveCall(
        '$packageAddress::liquidation_vault::balance',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}
