// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './price_info.dart' as price_info;

const $moduleName =
    '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837::batch_price_attestation';

final Header = Bcs.struct('${$moduleName}::Header', {
  'magic': SuiBcs.U64,
  'version_major': SuiBcs.U64,
  'version_minor': SuiBcs.U64,
  'header_size': SuiBcs.U64,
  'payload_id': SuiBcs.U8,
});

final BatchPriceAttestation =
    Bcs.struct('${$moduleName}::BatchPriceAttestation', {
  'header': Header,
  'attestation_size': SuiBcs.U64,
  'attestation_count': SuiBcs.U64,
  'price_infos': Bcs.vector(price_info.PriceInfo),
});

MoveCallBuilder destroy({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::batch_price_attestation::destroy',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getAttestationCount({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::batch_price_attestation::get_attestation_count',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getPriceInfo({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::batch_price_attestation::get_price_info',
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, [null, 'u64'], []),
      );
}

MoveCallBuilder deserialize({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::batch_price_attestation::deserialize',
        arguments: normalizeMoveArguments(tx, const <String, dynamic>{},
            ['vector<u8>', '0x2::clock::Clock'], []),
      );
}
