// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './price_feed.dart' as price_feed;

const $moduleName =
    '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837::event';

final PythInitializationEvent =
    Bcs.struct('${$moduleName}::PythInitializationEvent', {
  'dummy_field': SuiBcs.BOOL,
});

final PriceFeedUpdateEvent =
    Bcs.struct('${$moduleName}::PriceFeedUpdateEvent', {
  'price_feed': price_feed.PriceFeed,
  'timestamp': SuiBcs.U64,
});
