// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './governance_action.dart' as governance_action;

const $moduleName =
    '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837::governance_instruction';

final GovernanceInstruction =
    Bcs.struct('${$moduleName}::GovernanceInstruction', {
  'module_': SuiBcs.U8,
  'action': governance_action.GovernanceAction,
  'target_chain_id': SuiBcs.U64,
  'payload': Bcs.vector(SuiBcs.U8),
});

MoveCallBuilder fromByteVec({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::governance_instruction::from_byte_vec',
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, ['vector<u8>'], []),
      );
}

MoveCallBuilder getModule({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::governance_instruction::get_module',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getAction({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::governance_instruction::get_action',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getTargetChainId({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::governance_instruction::get_target_chain_id',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder destroy({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::governance_instruction::destroy',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}
