// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';

const $moduleName =
    '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837::hot_potato_vector';

BcsType<Map<String, dynamic>, dynamic> HotPotatoVector(
        BcsType<dynamic, dynamic> t0) =>
    Bcs.struct('${$moduleName}::HotPotatoVector<${t0.name}>', {
      'contents': Bcs.vector(t0),
    });

MoveCallBuilder destroy(
    {String? package, List<String> typeArguments = const []}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::hot_potato_vector::destroy',
        typeArguments: typeArguments,
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder length(
    {String? package, List<String> typeArguments = const []}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::hot_potato_vector::length',
        typeArguments: typeArguments,
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder isEmpty(
    {String? package, List<String> typeArguments = const []}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::hot_potato_vector::is_empty',
        typeArguments: typeArguments,
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}
