// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './price_feed.dart' as price_feed;

const $moduleName =
    '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837::price_info';

final PriceInfo = Bcs.struct('${$moduleName}::PriceInfo', {
  'attestation_time': SuiBcs.U64,
  'arrival_time': SuiBcs.U64,
  'price_feed': price_feed.PriceFeed,
});

final PriceInfoObject = Bcs.struct('${$moduleName}::PriceInfoObject', {
  'id': SuiBcs.Address,
  'price_info': PriceInfo,
});

MoveCallBuilder getIdBytes({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_info::get_id_bytes',
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, ['0x2::object::ID', null], []),
      );
}

MoveCallBuilder getId({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_info::get_id',
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, ['0x2::object::ID', null], []),
      );
}

MoveCallBuilder contains({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_info::contains',
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, ['0x2::object::ID', null], []),
      );
}

MoveCallBuilder getBalance({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_info::get_balance',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder depositFeeCoins({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_info::deposit_fee_coins',
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, [null, null], []),
      );
}

MoveCallBuilder newPriceInfo({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_info::new_price_info',
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, ['u64', 'u64', null], []),
      );
}

MoveCallBuilder uidToInner({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_info::uid_to_inner',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getPriceInfoFromPriceInfoObject({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_info::get_price_info_from_price_info_object',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getPriceIdentifier({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_info::get_price_identifier',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getPriceFeed({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_info::get_price_feed',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getAttestationTime({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_info::get_attestation_time',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getArrivalTime({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_info::get_arrival_time',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}
