// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './price_identifier.dart' as price_identifier;
import './price.dart' as price;

const $moduleName =
    '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837::price_feed';

final PriceFeed = Bcs.struct('${$moduleName}::PriceFeed', {
  'price_identifier': price_identifier.PriceIdentifier,
  'price': price.Price,
  'ema_price': price.Price,
});

MoveCallBuilder new_({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_feed::new',
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, [null, null, null], []),
      );
}

MoveCallBuilder from({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_feed::from',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getPriceIdentifier({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_feed::get_price_identifier',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getPrice({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_feed::get_price',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getEmaPrice({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::price_feed::get_ema_price',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}
