// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';

MoveCallBuilder initPyth({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::pyth::init_pyth',
        arguments: normalizeMoveArguments(tx, const <String, dynamic>{}, [
          null,
          null,
          'u64',
          'u64',
          'vector<u8>',
          'vector<u64>',
          'vector<vector<u8>>',
          'u64'
        ], []),
      );
}

MoveCallBuilder createPriceFeedsUsingAccumulator({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::pyth::create_price_feeds_using_accumulator',
        arguments: normalizeMoveArguments(tx, const <String, dynamic>{},
            [null, 'vector<u8>', null, '0x2::clock::Clock'], []),
      );
}

MoveCallBuilder createPriceFeeds({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::pyth::create_price_feeds',
        arguments: normalizeMoveArguments(tx, const <String, dynamic>{},
            [null, 'vector<null>', '0x2::clock::Clock'], []),
      );
}

MoveCallBuilder createAuthenticatedPriceInfosUsingAccumulator(
    {String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::pyth::create_authenticated_price_infos_using_accumulator',
        arguments: normalizeMoveArguments(tx, const <String, dynamic>{},
            [null, 'vector<u8>', null, '0x2::clock::Clock'], []),
      );
}

MoveCallBuilder createPriceInfosHotPotato({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::pyth::create_price_infos_hot_potato',
        arguments: normalizeMoveArguments(tx, const <String, dynamic>{},
            [null, 'vector<null>', '0x2::clock::Clock'], []),
      );
}

MoveCallBuilder updateSinglePriceFeed({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::pyth::update_single_price_feed',
        arguments: normalizeMoveArguments(tx, const <String, dynamic>{},
            [null, null, null, null, '0x2::clock::Clock'], []),
      );
}

MoveCallBuilder priceFeedExists({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::pyth::price_feed_exists',
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, [null, null], []),
      );
}

MoveCallBuilder getPrice({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::pyth::get_price',
        arguments: normalizeMoveArguments(tx, const <String, dynamic>{},
            [null, null, '0x2::clock::Clock'], []),
      );
}

MoveCallBuilder getPriceNoOlderThan({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::pyth::get_price_no_older_than',
        arguments: normalizeMoveArguments(tx, const <String, dynamic>{},
            [null, '0x2::clock::Clock', 'u64'], []),
      );
}

MoveCallBuilder getPriceUnsafe({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::pyth::get_price_unsafe',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getStalePriceThresholdSecs({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::pyth::get_stale_price_threshold_secs',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getTotalUpdateFee({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::pyth::get_total_update_fee',
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, [null, 'u64'], []),
      );
}
