// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/0x0000000000000000000000000000000000000000000000000000000000000002/table.dart'
    as table;

const $moduleName =
    '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837::set';

final Unit = Bcs.struct('${$moduleName}::Unit', {
  'dummy_field': SuiBcs.BOOL,
});

BcsType<Map<String, dynamic>, dynamic> Set(BcsType<dynamic, dynamic> t0) =>
    Bcs.struct('${$moduleName}::Set<${t0.name}>', {
      'keys': Bcs.vector(t0),
      'elems': table.Table,
    });

MoveCallBuilder new_({String? package, List<String> typeArguments = const []}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::set::new',
        typeArguments: typeArguments,
      );
}

MoveCallBuilder add({String? package, List<String> typeArguments = const []}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::set::add',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, [null, typeArguments[0]], []),
      );
}

MoveCallBuilder contains(
    {String? package, List<String> typeArguments = const []}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::set::contains',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, [null, typeArguments[0]], []),
      );
}

MoveCallBuilder empty(
    {String? package, List<String> typeArguments = const []}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::set::empty',
        typeArguments: typeArguments,
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}
