// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './data_source.dart' as data_source;
import './deps/0xf47329f4344f3bf0f8e436e2f7b485466cff300f12a166563995d3888c296a94/consumed_vaas.dart'
    as consumed_vaas;
import './deps/0x0000000000000000000000000000000000000000000000000000000000000002/package.dart'
    as package;

const $moduleName =
    '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837::state';

final LatestOnly = Bcs.struct('${$moduleName}::LatestOnly', {
  'dummy_field': SuiBcs.BOOL,
});

final State = Bcs.struct('${$moduleName}::State', {
  'id': SuiBcs.Address,
  'governance_data_source': data_source.DataSource,
  'stale_price_threshold': SuiBcs.U64,
  'base_update_fee': SuiBcs.U64,
  'fee_recipient_address': SuiBcs.Address,
  'last_executed_governance_sequence': SuiBcs.U64,
  'consumed_vaas': consumed_vaas.ConsumedVAAs,
  'upgrade_cap': package.UpgradeCap,
});

final CurrentDigest = Bcs.struct('${$moduleName}::CurrentDigest', {
  'dummy_field': SuiBcs.BOOL,
});

MoveCallBuilder getStalePriceThresholdSecs({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::state::get_stale_price_threshold_secs',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getBaseUpdateFee({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::state::get_base_update_fee',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getFeeRecipient({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::state::get_fee_recipient',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder isValidDataSource({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::state::is_valid_data_source',
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, [null, null], []),
      );
}

MoveCallBuilder isValidGovernanceDataSource({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::state::is_valid_governance_data_source',
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, [null, null], []),
      );
}

MoveCallBuilder priceFeedObjectExists({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::state::price_feed_object_exists',
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, [null, null], []),
      );
}

MoveCallBuilder governanceDataSource({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::state::governance_data_source',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getLastExecutedGovernanceSequence({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::state::get_last_executed_governance_sequence',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder governanceModule({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::state::governance_module',
      );
}

MoveCallBuilder governanceChain({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::state::governance_chain',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder governanceContract({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::state::governance_contract',
        arguments:
            normalizeMoveArguments(tx, const <String, dynamic>{}, [null], []),
      );
}

MoveCallBuilder getPriceInfoObjectId({String? package}) {
  final packageAddress = package ??
      '0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837';
  return (tx) => tx.moveCall(
        '$packageAddress::state::get_price_info_object_id',
        arguments: normalizeMoveArguments(
            tx, const <String, dynamic>{}, [null, 'vector<u8>'], []),
      );
}
