// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/sui/vec_set.dart' as vec_set;
import './balances.dart' as balances;

const $moduleName = '@deepbook/core::account';

final Account = Bcs.struct('${$moduleName}::Account', {
  'epoch': SuiBcs.U64,
  'open_orders': vec_set.VecSet(SuiBcs.U128),
  'taker_volume': SuiBcs.U128,
  'maker_volume': SuiBcs.U128,
  'active_stake': SuiBcs.U64,
  'inactive_stake': SuiBcs.U64,
  'created_proposal': SuiBcs.BOOL,
  'voted_proposal': Bcs.option(SuiBcs.Address),
  'unclaimed_rebates': balances.Balances,
  'settled_balances': balances.Balances,
  'owed_balances': balances.Balances,
});

MoveCallBuilder openOrders({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::account::open_orders',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder takerVolume({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::account::taker_volume',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder makerVolume({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::account::maker_volume',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder totalVolume({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::account::total_volume',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder activeStake({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::account::active_stake',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder inactiveStake({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::account::inactive_stake',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder createdProposal({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::account::created_proposal',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder votedProposal({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::account::voted_proposal',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder settledBalances({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::account::settled_balances',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}
