// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/sui/bag.dart' as bag;
import './deps/sui/vec_set.dart' as vec_set;
import './deps/std/type_name.dart' as type_name;

const $moduleName = '@deepbook/core::balance_manager';

final BalanceManager = Bcs.struct('${$moduleName}::BalanceManager', {
  'id': SuiBcs.Address,
  'owner': SuiBcs.Address,
  'balances': bag.Bag,
  'allow_listed': vec_set.VecSet(SuiBcs.Address),
});

final BalanceManagerEvent = Bcs.struct('${$moduleName}::BalanceManagerEvent', {
  'balance_manager_id': SuiBcs.Address,
  'owner': SuiBcs.Address,
});

final BalanceEvent = Bcs.struct('${$moduleName}::BalanceEvent', {
  'balance_manager_id': SuiBcs.Address,
  'asset': type_name.TypeName,
  'amount': SuiBcs.U64,
  'deposit': SuiBcs.BOOL,
});

final BalanceKey = Bcs.struct('${$moduleName}::BalanceKey<phantom T>', {
  'dummy_field': SuiBcs.BOOL,
});

final ReferralKey = Bcs.tuple(
    [SuiBcs.Address], BcsTypeOptions(name: '${$moduleName}::ReferralKey'));

final TradeCap = Bcs.struct('${$moduleName}::TradeCap', {
  'id': SuiBcs.Address,
  'balance_manager_id': SuiBcs.Address,
});

final DepositCap = Bcs.struct('${$moduleName}::DepositCap', {
  'id': SuiBcs.Address,
  'balance_manager_id': SuiBcs.Address,
});

final WithdrawCap = Bcs.struct('${$moduleName}::WithdrawCap', {
  'id': SuiBcs.Address,
  'balance_manager_id': SuiBcs.Address,
});

final DeepBookReferral = Bcs.struct('${$moduleName}::DeepBookReferral', {
  'id': SuiBcs.Address,
  'owner': SuiBcs.Address,
});

final DeepBookPoolReferral =
    Bcs.struct('${$moduleName}::DeepBookPoolReferral', {
  'id': SuiBcs.Address,
  'owner': SuiBcs.Address,
  'pool_id': SuiBcs.Address,
});

final DeepBookReferralCreatedEvent =
    Bcs.struct('${$moduleName}::DeepBookReferralCreatedEvent', {
  'referral_id': SuiBcs.Address,
  'owner': SuiBcs.Address,
});

final DeepBookReferralSetEvent =
    Bcs.struct('${$moduleName}::DeepBookReferralSetEvent', {
  'referral_id': SuiBcs.Address,
  'balance_manager_id': SuiBcs.Address,
});

final TradeProof = Bcs.struct('${$moduleName}::TradeProof', {
  'balance_manager_id': SuiBcs.Address,
  'trader': SuiBcs.Address,
});

MoveCallBuilder new_({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::new',
      );
}

MoveCallBuilder newWithOwner({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::new_with_owner',
        arguments:
            normalizeMoveArguments(tx, arguments, ['address'], ['Owner']),
      );
}

/// Create a new balance manager with an owner.
MoveCallBuilder newWithCustomOwner(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::new_with_custom_owner',
        arguments:
            normalizeMoveArguments(tx, arguments, ['address'], ['owner']),
      );
}

MoveCallBuilder newWithCustomOwnerAndCaps(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::new_with_custom_owner_and_caps',
        arguments:
            normalizeMoveArguments(tx, arguments, ['address'], ['Owner']),
      );
}

MoveCallBuilder newWithCustomOwnerCaps(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::new_with_custom_owner_caps',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, 'address'], ['DeepbookRegistry', 'Owner']),
      );
}

/// Create a `BalanceManager` with all three caps, gated on an authorized `App`
/// witness. The witness ensures only the module defining `App` can mint caps for
/// that app — the type tag alone is referenceable from any module, so the previous
/// `<App>`-only signature let a rogue caller mint caps under another app's
/// identity.
MoveCallBuilder newWithCustomOwnerCapsV2(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::new_with_custom_owner_caps_v2',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [typeArguments[0], null, 'address'],
            ['Witness', 'deepbookRegistry', 'owner']),
      );
}

MoveCallBuilder setReferral({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::set_referral',
        arguments: normalizeMoveArguments(tx, arguments, [null, null, null],
            ['BalanceManager', 'Referral', 'TradeCap']),
      );
}

/// Set the referral for the balance manager.
MoveCallBuilder setBalanceManagerReferral(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::set_balance_manager_referral',
        arguments: normalizeMoveArguments(tx, arguments, [null, null, null],
            ['balanceManager', 'referral', 'tradeCap']),
      );
}

MoveCallBuilder unsetReferral({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::unset_referral',
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['BalanceManager', 'TradeCap']),
      );
}

/// Unset the referral for the balance manager.
MoveCallBuilder unsetBalanceManagerReferral(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::unset_balance_manager_referral',
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, '0x2::object::ID', null],
            ['balanceManager', 'poolId', 'tradeCap']),
      );
}

/// Returns the balance of a Coin in a balance manager.
MoveCallBuilder balance(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::balance',
        typeArguments: typeArguments,
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['balanceManager']),
      );
}

/// Mint a `TradeCap`, only owner can mint a `TradeCap`.
MoveCallBuilder mintTradeCap({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::mint_trade_cap',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['balanceManager']),
      );
}

/// Mint a `DepositCap`, only owner can mint.
MoveCallBuilder mintDepositCap({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::mint_deposit_cap',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['balanceManager']),
      );
}

/// Mint a `WithdrawCap`, only owner can mint.
MoveCallBuilder mintWithdrawCap({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::mint_withdraw_cap',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['balanceManager']),
      );
}

/// Revoke a `TradeCap`. Only the owner can revoke a `TradeCap`. Can also be used to
/// revoke `DepositCap` and `WithdrawCap`.
MoveCallBuilder revokeTradeCap({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::revoke_trade_cap',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, '0x2::object::ID'], ['balanceManager', 'tradeCapId']),
      );
}

/// Generate a `TradeProof` by the owner. The owner does not require a capability
/// and can generate TradeProofs without the risk of equivocation.
MoveCallBuilder generateProofAsOwner(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::generate_proof_as_owner',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['balanceManager']),
      );
}

/// Generate a `TradeProof` with a `TradeCap`. Risk of equivocation since `TradeCap`
/// is an owned object.
MoveCallBuilder generateProofAsTrader(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::generate_proof_as_trader',
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['balanceManager', 'tradeCap']),
      );
}

/// Deposit funds to a balance manager. Only owner can call this directly.
MoveCallBuilder deposit(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::deposit',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['balanceManager', 'coin']),
      );
}

/// Deposit funds into a balance manager by a `DepositCap` owner.
MoveCallBuilder depositWithCap(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::deposit_with_cap',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, null],
            ['balanceManager', 'depositCap', 'coin']),
      );
}

/// Withdraw funds from a balance manager by a `WithdrawCap` owner.
MoveCallBuilder withdrawWithCap(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::withdraw_with_cap',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, 'u64'],
            ['balanceManager', 'withdrawCap', 'withdrawAmount']),
      );
}

/// Withdraw funds from a balance_manager. Only owner can call this directly. If
/// withdraw_all is true, amount is ignored and full balance withdrawn. If
/// withdraw_all is false, withdraw_amount will be withdrawn.
MoveCallBuilder withdraw(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::withdraw',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, 'u64'], ['balanceManager', 'withdrawAmount']),
      );
}

MoveCallBuilder withdrawAll(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::withdraw_all',
        typeArguments: typeArguments,
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['balanceManager']),
      );
}

MoveCallBuilder registerManager({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::register_manager',
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['BalanceManager', 'Registry']),
      );
}

MoveCallBuilder registerBalanceManager(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::register_balance_manager',
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['balanceManager', 'registry']),
      );
}

MoveCallBuilder getReferralId({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::get_referral_id',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['BalanceManager']),
      );
}

/// Get the referral id from the balance manager.
MoveCallBuilder getBalanceManagerReferralId(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::get_balance_manager_referral_id',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, '0x2::object::ID'], ['balanceManager', 'poolId']),
      );
}

MoveCallBuilder validateProof({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::validate_proof',
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['balanceManager', 'proof']),
      );
}

/// Returns the owner of the balance_manager.
MoveCallBuilder owner({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::owner',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['balanceManager']),
      );
}

/// Returns the owner of the balance_manager.
MoveCallBuilder id({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::id',
        arguments:
            normalizeMoveArguments(tx, arguments, [null], ['balanceManager']),
      );
}

MoveCallBuilder referralOwner({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::referral_owner',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['Referral']),
      );
}

MoveCallBuilder balanceManagerReferralOwner(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::balance_manager_referral_owner',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['referral']),
      );
}

MoveCallBuilder balanceManagerReferralPoolId(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::balance_manager::balance_manager_referral_pool_id',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['referral']),
      );
}
