// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';

const $moduleName = '@deepbook/core::big_vector';

final BigVector = Bcs.struct('${$moduleName}::BigVector<phantom E>', {
  'id': SuiBcs.Address,
  'depth': SuiBcs.U8,
  'length': SuiBcs.U64,
  'max_slice_size': SuiBcs.U64,
  'max_fan_out': SuiBcs.U64,
  'root_id': SuiBcs.U64,
  'last_id': SuiBcs.U64,
});

/// A node in the B+ tree.
///
/// If representing a leaf node, there are as many keys as values (such that
/// `keys[i]` is the key corresponding to `vals[i]`).
///
/// A `Slice<u64>` can also represent an interior node, in which case `vals` contain
/// the IDs of its children and `keys` represent the partitions between children.
/// There will be one fewer key than value in this configuration.
BcsType<Map<String, dynamic>, dynamic> Slice(BcsType<dynamic, dynamic> t0) =>
    Bcs.struct('${$moduleName}::Slice<${t0.name}>', {
      'prev': SuiBcs.U64,
      'next': SuiBcs.U64,
      'keys': Bcs.vector(SuiBcs.U128),
      'vals': Bcs.vector(t0),
    });

final SliceRef = Bcs.struct('${$moduleName}::SliceRef', {
  'ix': SuiBcs.U64,
});
