// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './big_vector.dart' as big_vector;

const $moduleName = '@deepbook/core::book';

final Book = Bcs.struct('${$moduleName}::Book', {
  'tick_size': SuiBcs.U64,
  'lot_size': SuiBcs.U64,
  'min_size': SuiBcs.U64,
  'bids': big_vector.BigVector,
  'asks': big_vector.BigVector,
  'next_bid_order_id': SuiBcs.U64,
  'next_ask_order_id': SuiBcs.U64,
});
