// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';

MoveCallBuilder currentVersion({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::current_version',
      );
}

MoveCallBuilder poolCreationFee({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::pool_creation_fee',
      );
}

MoveCallBuilder floatScaling({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::float_scaling',
      );
}

MoveCallBuilder floatScalingU128({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::float_scaling_u128',
      );
}

MoveCallBuilder maxU64({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::max_u64',
      );
}

MoveCallBuilder maxU128({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::max_u128',
      );
}

MoveCallBuilder noRestriction({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::no_restriction',
      );
}

MoveCallBuilder immediateOrCancel({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::immediate_or_cancel',
      );
}

MoveCallBuilder fillOrKill({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::fill_or_kill',
      );
}

MoveCallBuilder postOnly({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::post_only',
      );
}

MoveCallBuilder maxRestriction({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::max_restriction',
      );
}

MoveCallBuilder live({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::live',
      );
}

MoveCallBuilder partiallyFilled({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::partially_filled',
      );
}

MoveCallBuilder filled({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::filled',
      );
}

MoveCallBuilder canceled({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::canceled',
      );
}

MoveCallBuilder expired({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::expired',
      );
}

MoveCallBuilder selfMatchingAllowed({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::self_matching_allowed',
      );
}

MoveCallBuilder cancelTaker({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::cancel_taker',
      );
}

MoveCallBuilder cancelMaker({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::cancel_maker',
      );
}

MoveCallBuilder minPrice({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::min_price',
      );
}

MoveCallBuilder maxPrice({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::max_price',
      );
}

MoveCallBuilder phaseOutEpochs({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::phase_out_epochs',
      );
}

MoveCallBuilder defaultStakeRequired({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::default_stake_required',
      );
}

MoveCallBuilder maxStakeRequired({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::max_stake_required',
      );
}

MoveCallBuilder half({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::half',
      );
}

MoveCallBuilder feeIsDeep({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::fee_is_deep',
      );
}

MoveCallBuilder deepUnit({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::deep_unit',
      );
}

MoveCallBuilder maxFills({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::max_fills',
      );
}

MoveCallBuilder maxOpenOrders({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::max_open_orders',
      );
}

MoveCallBuilder maxSliceSize({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::max_slice_size',
      );
}

MoveCallBuilder maxFanOut({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::max_fan_out',
      );
}

MoveCallBuilder feePenaltyMultiplier({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::fee_penalty_multiplier',
      );
}

MoveCallBuilder defaultEwmaAlpha({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::default_ewma_alpha',
      );
}

MoveCallBuilder defaultZScoreThreshold({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::default_z_score_threshold',
      );
}

MoveCallBuilder defaultAdditionalTakerFee({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::default_additional_taker_fee',
      );
}

MoveCallBuilder maxEwmaAlpha({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::max_ewma_alpha',
      );
}

MoveCallBuilder maxZScoreThreshold({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::max_z_score_threshold',
      );
}

MoveCallBuilder maxAdditionalTakerFee({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::max_additional_taker_fee',
      );
}

MoveCallBuilder ewmaDfKey({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::ewma_df_key',
      );
}

MoveCallBuilder referralMaxMultiplier({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::referral_max_multiplier',
      );
}

MoveCallBuilder referralMultiplier({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::referral_multiplier',
      );
}

MoveCallBuilder maxBalanceManagers({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::max_balance_managers',
      );
}

MoveCallBuilder referralDfKey({String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::constants::referral_df_key',
      );
}
