// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';

const $moduleName = '@deepbook/core::deep_price';

final Price = Bcs.struct('${$moduleName}::Price', {
  'conversion_rate': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

final PriceAdded = Bcs.struct('${$moduleName}::PriceAdded', {
  'conversion_rate': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
  'is_base_conversion': SuiBcs.BOOL,
  'reference_pool': SuiBcs.Address,
  'target_pool': SuiBcs.Address,
});

final DeepPrice = Bcs.struct('${$moduleName}::DeepPrice', {
  'base_prices': Bcs.vector(Price),
  'cumulative_base': SuiBcs.U64,
  'quote_prices': Bcs.vector(Price),
  'cumulative_quote': SuiBcs.U64,
});

final OrderDeepPrice = Bcs.struct('${$moduleName}::OrderDeepPrice', {
  'asset_is_base': SuiBcs.BOOL,
  'deep_per_asset': SuiBcs.U64,
});

MoveCallBuilder assetIsBase({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::deep_price::asset_is_base',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder deepPerAsset({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::deep_price::deep_per_asset',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}
