// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';

const $moduleName = '@deepbook/core::ewma';

final EWMAState = Bcs.struct('${$moduleName}::EWMAState', {
  'mean': SuiBcs.U64,
  'variance': SuiBcs.U64,
  'alpha': SuiBcs.U64,
  'z_score_threshold': SuiBcs.U64,
  'additional_taker_fee': SuiBcs.U64,
  'last_updated_timestamp': SuiBcs.U64,
  'enabled': SuiBcs.BOOL,
});

final EWMAUpdate = Bcs.struct('${$moduleName}::EWMAUpdate', {
  'pool_id': SuiBcs.Address,
  'gas_price': SuiBcs.U64,
  'mean': SuiBcs.U64,
  'variance': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});
