// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/sui/vec_map.dart' as vec_map;
import './trade_params.dart' as trade_params;

const $moduleName = '@deepbook/core::governance';

final Proposal = Bcs.struct('${$moduleName}::Proposal', {
  'taker_fee': SuiBcs.U64,
  'maker_fee': SuiBcs.U64,
  'stake_required': SuiBcs.U64,
  'votes': SuiBcs.U64,
});

final Governance = Bcs.struct('${$moduleName}::Governance', {
  'epoch': SuiBcs.U64,
  'whitelisted': SuiBcs.BOOL,
  'stable': SuiBcs.BOOL,
  'proposals': vec_map.VecMap(SuiBcs.Address, Proposal),
  'trade_params': trade_params.TradeParams,
  'next_trade_params': trade_params.TradeParams,
  'voting_power': SuiBcs.U64,
  'quorum': SuiBcs.U64,
});

final TradeParamsUpdateEvent =
    Bcs.struct('${$moduleName}::TradeParamsUpdateEvent', {
  'taker_fee': SuiBcs.U64,
  'maker_fee': SuiBcs.U64,
  'stake_required': SuiBcs.U64,
});
