// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './balances.dart' as balances;
import './trade_params.dart' as trade_params;
import './deps/sui/table.dart' as table;

const $moduleName = '@deepbook/core::history';

final Volumes = Bcs.struct('${$moduleName}::Volumes', {
  'total_volume': SuiBcs.U128,
  'total_staked_volume': SuiBcs.U128,
  'total_fees_collected': balances.Balances,
  'historic_median': SuiBcs.U128,
  'trade_params': trade_params.TradeParams,
});

final History = Bcs.struct('${$moduleName}::History', {
  'epoch': SuiBcs.U64,
  'epoch_created': SuiBcs.U64,
  'volumes': Volumes,
  'historic_volumes': table.Table,
  'balance_to_burn': SuiBcs.U64,
});

final EpochData = Bcs.struct('${$moduleName}::EpochData', {
  'epoch': SuiBcs.U64,
  'pool_id': SuiBcs.Address,
  'total_volume': SuiBcs.U128,
  'total_staked_volume': SuiBcs.U128,
  'base_fees_collected': SuiBcs.U64,
  'quote_fees_collected': SuiBcs.U64,
  'deep_fees_collected': SuiBcs.U64,
  'historic_median': SuiBcs.U128,
  'taker_fee': SuiBcs.U64,
  'maker_fee': SuiBcs.U64,
  'stake_required': SuiBcs.U64,
});
