// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';

/// Multiply two floating numbers. This function will round down the result.
MoveCallBuilder mul({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::math::mul',
        arguments:
            normalizeMoveArguments(tx, arguments, ['u64', 'u64'], ['x', 'y']),
      );
}

MoveCallBuilder mulU128({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::math::mul_u128',
        arguments:
            normalizeMoveArguments(tx, arguments, ['u128', 'u128'], ['x', 'y']),
      );
}

/// Multiply two floating numbers. This function will round up the result.
MoveCallBuilder mulRoundUp({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::math::mul_round_up',
        arguments:
            normalizeMoveArguments(tx, arguments, ['u64', 'u64'], ['x', 'y']),
      );
}

/// Divide two floating numbers. This function will round down the result.
MoveCallBuilder div({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::math::div',
        arguments:
            normalizeMoveArguments(tx, arguments, ['u64', 'u64'], ['x', 'y']),
      );
}

MoveCallBuilder divU128({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::math::div_u128',
        arguments:
            normalizeMoveArguments(tx, arguments, ['u128', 'u128'], ['x', 'y']),
      );
}

/// Divide two floating numbers. This function will round up the result.
MoveCallBuilder divRoundUp({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::math::div_round_up',
        arguments:
            normalizeMoveArguments(tx, arguments, ['u64', 'u64'], ['x', 'y']),
      );
}

/// given a vector of u128, return the median
MoveCallBuilder median({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::math::median',
        arguments:
            normalizeMoveArguments(tx, arguments, ['vector<u128>'], ['v']),
      );
}

/// Computes the integer square root of a scaled u64 value, assuming the original
/// value is scaled by precision. The result will be in the same floating-point
/// representation.
MoveCallBuilder sqrt({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::math::sqrt',
        arguments: normalizeMoveArguments(
            tx, arguments, ['u64', 'u64'], ['x', 'precision']),
      );
}

MoveCallBuilder isPowerOfTen({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::math::is_power_of_ten',
        arguments: normalizeMoveArguments(tx, arguments, ['u64'], ['n']),
      );
}
