// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deep_price.dart' as deep_price;
import './fill.dart' as fill;

const $moduleName = '@deepbook/core::order_info';

final OrderInfo = Bcs.struct('${$moduleName}::OrderInfo', {
  'pool_id': SuiBcs.Address,
  'order_id': SuiBcs.U128,
  'balance_manager_id': SuiBcs.Address,
  'client_order_id': SuiBcs.U64,
  'trader': SuiBcs.Address,
  'order_type': SuiBcs.U8,
  'self_matching_option': SuiBcs.U8,
  'price': SuiBcs.U64,
  'is_bid': SuiBcs.BOOL,
  'original_quantity': SuiBcs.U64,
  'order_deep_price': deep_price.OrderDeepPrice,
  'expire_timestamp': SuiBcs.U64,
  'executed_quantity': SuiBcs.U64,
  'cumulative_quote_quantity': SuiBcs.U64,
  'fills': Bcs.vector(fill.Fill),
  'fee_is_deep': SuiBcs.BOOL,
  'paid_fees': SuiBcs.U64,
  'maker_fees': SuiBcs.U64,
  'epoch': SuiBcs.U64,
  'status': SuiBcs.U8,
  'market_order': SuiBcs.BOOL,
  'fill_limit_reached': SuiBcs.BOOL,
  'order_inserted': SuiBcs.BOOL,
  'timestamp': SuiBcs.U64,
});

final OrderFilled = Bcs.struct('${$moduleName}::OrderFilled', {
  'pool_id': SuiBcs.Address,
  'maker_order_id': SuiBcs.U128,
  'taker_order_id': SuiBcs.U128,
  'maker_client_order_id': SuiBcs.U64,
  'taker_client_order_id': SuiBcs.U64,
  'price': SuiBcs.U64,
  'taker_is_bid': SuiBcs.BOOL,
  'taker_fee': SuiBcs.U64,
  'taker_fee_is_deep': SuiBcs.BOOL,
  'maker_fee': SuiBcs.U64,
  'maker_fee_is_deep': SuiBcs.BOOL,
  'base_quantity': SuiBcs.U64,
  'quote_quantity': SuiBcs.U64,
  'maker_balance_manager_id': SuiBcs.Address,
  'taker_balance_manager_id': SuiBcs.Address,
  'timestamp': SuiBcs.U64,
});

final OrderPlaced = Bcs.struct('${$moduleName}::OrderPlaced', {
  'balance_manager_id': SuiBcs.Address,
  'pool_id': SuiBcs.Address,
  'order_id': SuiBcs.U128,
  'client_order_id': SuiBcs.U64,
  'trader': SuiBcs.Address,
  'price': SuiBcs.U64,
  'is_bid': SuiBcs.BOOL,
  'placed_quantity': SuiBcs.U64,
  'expire_timestamp': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

final OrderExpired = Bcs.struct('${$moduleName}::OrderExpired', {
  'balance_manager_id': SuiBcs.Address,
  'pool_id': SuiBcs.Address,
  'order_id': SuiBcs.U128,
  'client_order_id': SuiBcs.U64,
  'trader': SuiBcs.Address,
  'price': SuiBcs.U64,
  'is_bid': SuiBcs.BOOL,
  'original_quantity': SuiBcs.U64,
  'base_asset_quantity_canceled': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

final OrderFullyFilled = Bcs.struct('${$moduleName}::OrderFullyFilled', {
  'pool_id': SuiBcs.Address,
  'order_id': SuiBcs.U128,
  'client_order_id': SuiBcs.U64,
  'balance_manager_id': SuiBcs.Address,
  'original_quantity': SuiBcs.U64,
  'is_bid': SuiBcs.BOOL,
  'timestamp': SuiBcs.U64,
});

MoveCallBuilder poolId({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::pool_id',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder orderId({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::order_id',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder balanceManagerId(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::balance_manager_id',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder clientOrderId({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::client_order_id',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder trader({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::trader',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder orderType({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::order_type',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder selfMatchingOption(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::self_matching_option',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder price({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::price',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder isBid({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::is_bid',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder originalQuantity(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::original_quantity',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder orderDeepPrice({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::order_deep_price',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder expireTimestamp({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::expire_timestamp',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder executedQuantity(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::executed_quantity',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder cumulativeQuoteQuantity(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::cumulative_quote_quantity',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder fills({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::fills',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder feeIsDeep({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::fee_is_deep',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder paidFees({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::paid_fees',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder makerFees({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::maker_fees',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder epoch({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::epoch',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder status({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::status',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder fillLimitReached(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::fill_limit_reached',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder orderInserted({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_info::order_inserted',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}
