// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deep_price.dart' as deep_price;

const $moduleName = '@deepbook/core::order';

final Order = Bcs.struct('${$moduleName}::Order', {
  'balance_manager_id': SuiBcs.Address,
  'order_id': SuiBcs.U128,
  'client_order_id': SuiBcs.U64,
  'quantity': SuiBcs.U64,
  'filled_quantity': SuiBcs.U64,
  'fee_is_deep': SuiBcs.BOOL,
  'order_deep_price': deep_price.OrderDeepPrice,
  'epoch': SuiBcs.U64,
  'status': SuiBcs.U8,
  'expire_timestamp': SuiBcs.U64,
});

final OrderCanceled = Bcs.struct('${$moduleName}::OrderCanceled', {
  'balance_manager_id': SuiBcs.Address,
  'pool_id': SuiBcs.Address,
  'order_id': SuiBcs.U128,
  'client_order_id': SuiBcs.U64,
  'trader': SuiBcs.Address,
  'price': SuiBcs.U64,
  'is_bid': SuiBcs.BOOL,
  'original_quantity': SuiBcs.U64,
  'base_asset_quantity_canceled': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

final OrderModified = Bcs.struct('${$moduleName}::OrderModified', {
  'balance_manager_id': SuiBcs.Address,
  'pool_id': SuiBcs.Address,
  'order_id': SuiBcs.U128,
  'client_order_id': SuiBcs.U64,
  'trader': SuiBcs.Address,
  'price': SuiBcs.U64,
  'is_bid': SuiBcs.BOOL,
  'previous_quantity': SuiBcs.U64,
  'filled_quantity': SuiBcs.U64,
  'new_quantity': SuiBcs.U64,
  'timestamp': SuiBcs.U64,
});

MoveCallBuilder balanceManagerId(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order::balance_manager_id',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder orderId({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order::order_id',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder clientOrderId({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order::client_order_id',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder quantity({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order::quantity',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder filledQuantity({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order::filled_quantity',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder feeIsDeep({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order::fee_is_deep',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder orderDeepPrice({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order::order_deep_price',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder epoch({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order::epoch',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder status({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order::status',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder expireTimestamp({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order::expire_timestamp',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder price({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order::price',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}
