// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './order.dart' as order;

const $moduleName = '@deepbook/core::order_query';

final OrderPage = Bcs.struct('${$moduleName}::OrderPage', {
  'orders': Bcs.vector(order.Order),
  'has_next_page': SuiBcs.BOOL,
});

/// Bid minimum order id has 0 for its first bit, 0 for next 63 bits for price, and
/// 1 for next 64 bits for order id. Ask minimum order id has 1 for its first bit, 0
/// for next 63 bits for price, and 0 for next 64 bits for order id. Bids are
/// iterated from high to low order id, and asks are iterated from low to high order
/// id.
MoveCallBuilder iterOrders(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_query::iter_orders',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          '0x1::option::Option<u128>',
          '0x1::option::Option<u128>',
          '0x1::option::Option<u64>',
          'u64',
          'bool'
        ], [
          'self',
          'startOrderId',
          'endOrderId',
          'minExpireTimestamp',
          'limit',
          'bids'
        ]),
      );
}

MoveCallBuilder orders({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_query::orders',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder hasNextPage({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::order_query::has_next_page',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}
