// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/sui/versioned.dart' as versioned;
import './deps/sui/vec_set.dart' as vec_set;
import './book.dart' as book;
import './state.dart' as state;
import './vault.dart' as vault;
import './deep_price.dart' as deep_price;
import './deps/sui/balance.dart' as balance;

const $moduleName = '@deepbook/core::pool';

final Pool =
    Bcs.struct('${$moduleName}::Pool<phantom BaseAsset, phantom QuoteAsset>', {
  'id': SuiBcs.Address,
  'inner': versioned.Versioned,
});

final PoolInner = Bcs.struct(
    '${$moduleName}::PoolInner<phantom BaseAsset, phantom QuoteAsset>', {
  'allowed_versions': vec_set.VecSet(SuiBcs.U64),
  'pool_id': SuiBcs.Address,
  'book': book.Book,
  'state': state.State,
  'vault': vault.Vault,
  'deep_price': deep_price.DeepPrice,
  'registered_pool': SuiBcs.BOOL,
});

final PoolCreated = Bcs.struct(
    '${$moduleName}::PoolCreated<phantom BaseAsset, phantom QuoteAsset>', {
  'pool_id': SuiBcs.Address,
  'taker_fee': SuiBcs.U64,
  'maker_fee': SuiBcs.U64,
  'tick_size': SuiBcs.U64,
  'lot_size': SuiBcs.U64,
  'min_size': SuiBcs.U64,
  'whitelisted_pool': SuiBcs.BOOL,
  'treasury_address': SuiBcs.Address,
});

final BookParamsUpdated = Bcs.struct(
    '${$moduleName}::BookParamsUpdated<phantom BaseAsset, phantom QuoteAsset>',
    {
      'pool_id': SuiBcs.Address,
      'tick_size': SuiBcs.U64,
      'lot_size': SuiBcs.U64,
      'min_size': SuiBcs.U64,
      'timestamp': SuiBcs.U64,
    });

final DeepBurned = Bcs.struct(
    '${$moduleName}::DeepBurned<phantom BaseAsset, phantom QuoteAsset>', {
  'pool_id': SuiBcs.Address,
  'deep_burned': SuiBcs.U64,
});

final ReferralRewards = Bcs.struct(
    '${$moduleName}::ReferralRewards<phantom BaseAsset, phantom QuoteAsset>', {
  'multiplier': SuiBcs.U64,
  'base': balance.Balance,
  'quote': balance.Balance,
  'deep': balance.Balance,
});

final ReferralClaimedEvent = Bcs.struct(
    '${$moduleName}::ReferralClaimedEvent<phantom BaseAsset, phantom QuoteAsset>',
    {
      'referral_id': SuiBcs.Address,
      'owner': SuiBcs.Address,
      'base_amount': SuiBcs.U64,
      'quote_amount': SuiBcs.U64,
      'deep_amount': SuiBcs.U64,
    });

final ReferralClaimed = Bcs.struct('${$moduleName}::ReferralClaimed', {
  'pool_id': SuiBcs.Address,
  'referral_id': SuiBcs.Address,
  'owner': SuiBcs.Address,
  'base_amount': SuiBcs.U64,
  'quote_amount': SuiBcs.U64,
  'deep_amount': SuiBcs.U64,
});

final ReferralFeeEvent = Bcs.struct('${$moduleName}::ReferralFeeEvent', {
  'pool_id': SuiBcs.Address,
  'referral_id': SuiBcs.Address,
  'base_fee': SuiBcs.U64,
  'quote_fee': SuiBcs.U64,
  'deep_fee': SuiBcs.U64,
});

/// Create a new pool. The pool is registered in the registry. Checks are performed
/// to ensure the tick size, lot size, and min size are valid. The creation fee is
/// transferred to the treasury address. Returns the id of the pool created
MoveCallBuilder createPermissionlessPool(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::create_permissionless_pool',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, 'u64', 'u64', 'u64', null],
            ['registry', 'tickSize', 'lotSize', 'minSize', 'creationFee']),
      );
}

/// Place a limit order. Quantity is in base asset terms. For current version
/// pay_with_deep must be true, so the fee will be paid with DEEP tokens.
MoveCallBuilder placeLimitOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::place_limit_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          'u64',
          'u8',
          'u8',
          'u64',
          'u64',
          'bool',
          'bool',
          'u64',
          '0x2::clock::Clock'
        ], [
          'self',
          'balanceManager',
          'tradeProof',
          'clientOrderId',
          'orderType',
          'selfMatchingOption',
          'price',
          'quantity',
          'isBid',
          'payWithDeep',
          'expireTimestamp'
        ]),
      );
}

/// Graceful post-only limit order. Checks the relevant side of the book first and
/// only forwards to `place_limit_order` with `POST_ONLY` when the order is
/// guaranteed not to cross a live order the matcher can reach. Returns `none`
/// instead of aborting `EPOSTOrderCrossesOrderbook` when it would cross — and also
/// `none` when the forwarded placement rests nothing (a large expired backlog at a
/// crossing price makes `place_limit_order` hit its fill limit and inject no
/// order), so `some` always means the order is resting on the book. An empty
/// opposite side always allows placement.
///
/// Self-matching is fixed to `SELF_MATCHING_ALLOWED` and is not a parameter: the
/// wrapper only ever forwards a non-crossing order, and self-matching governs how a
/// _crossing_ fill treats the taker's own maker orders, so it has no effect on the
/// forwarded placement. Exposing it would also be a footgun — `CANCEL_TAKER` aborts
/// (`ESelfMatchingCancelTaker`) against the caller's own expired order sitting at a
/// crossing price, which the pre-check skips as non-live, re-introducing the very
/// abort this wrapper exists to avoid. A caller that wants to cross and cancel its
/// own resting orders should call `place_limit_order` directly.
MoveCallBuilder placePostOnlyLimitOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::place_post_only_limit_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          'u64',
          'u64',
          'u64',
          'bool',
          'bool',
          'u64',
          '0x2::clock::Clock'
        ], [
          'self',
          'balanceManager',
          'tradeProof',
          'clientOrderId',
          'price',
          'quantity',
          'isBid',
          'payWithDeep',
          'expireTimestamp'
        ]),
      );
}

/// Place a market order. Quantity is in base asset terms. Calls place_limit_order
/// with a price of MAX_PRICE for bids and MIN_PRICE for asks. Any quantity not
/// filled is cancelled.
MoveCallBuilder placeMarketOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::place_market_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          'u64',
          'u8',
          'u64',
          'bool',
          'bool',
          '0x2::clock::Clock'
        ], [
          'self',
          'balanceManager',
          'tradeProof',
          'clientOrderId',
          'selfMatchingOption',
          'quantity',
          'isBid',
          'payWithDeep'
        ]),
      );
}

/// Swap exact base quantity without needing a `balance_manager`. DEEP quantity can
/// be overestimated. Returns three `Coin` objects: base, quote, and deep. Some base
/// quantity may be left over, if the input quantity is not divisible by lot size.
MoveCallBuilder swapExactBaseForQuote(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::swap_exact_base_for_quote',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'u64', '0x2::clock::Clock'],
            ['self', 'baseIn', 'deepIn', 'minQuoteOut']),
      );
}

/// Swap exact base for quote with a `balance_manager`. Assumes fees are paid in
/// DEEP. Assumes balance manager has enough DEEP for fees.
MoveCallBuilder swapExactBaseForQuoteWithManager(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::swap_exact_base_for_quote_with_manager',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          'u64',
          '0x2::clock::Clock'
        ], [
          'self',
          'balanceManager',
          'tradeCap',
          'depositCap',
          'withdrawCap',
          'baseIn',
          'minQuoteOut'
        ]),
      );
}

/// Swap exact quote quantity without needing a `balance_manager`. DEEP quantity can
/// be overestimated. Returns three `Coin` objects: base, quote, and deep. Some
/// quote quantity may be left over if the input quantity is not divisible by lot
/// size.
MoveCallBuilder swapExactQuoteForBase(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::swap_exact_quote_for_base',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'u64', '0x2::clock::Clock'],
            ['self', 'quoteIn', 'deepIn', 'minBaseOut']),
      );
}

/// Swap exact quote for base with a `balance_manager`. Assumes fees are paid in
/// DEEP. Assumes balance manager has enough DEEP for fees.
MoveCallBuilder swapExactQuoteForBaseWithManager(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::swap_exact_quote_for_base_with_manager',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          'u64',
          '0x2::clock::Clock'
        ], [
          'self',
          'balanceManager',
          'tradeCap',
          'depositCap',
          'withdrawCap',
          'quoteIn',
          'minBaseOut'
        ]),
      );
}

/// Swap exact quantity without needing a balance_manager.
MoveCallBuilder swapExactQuantity(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::swap_exact_quantity',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, null, 'u64', '0x2::clock::Clock'],
            ['self', 'baseIn', 'quoteIn', 'deepIn', 'minOut']),
      );
}

/// Swap exact quantity with a `balance_manager`. Assumes fees are paid in DEEP.
/// Assumes balance manager has enough DEEP for fees.
MoveCallBuilder swapExactQuantityWithManager(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::swap_exact_quantity_with_manager',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          'u64',
          '0x2::clock::Clock'
        ], [
          'self',
          'balanceManager',
          'tradeCap',
          'depositCap',
          'withdrawCap',
          'baseIn',
          'quoteIn',
          'minOut'
        ]),
      );
}

/// Modifies an order given order_id and new_quantity. New quantity must be less
/// than the original quantity and more than the filled quantity. Order must not
/// have already expired.
MoveCallBuilder modifyOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::modify_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'u128', 'u64', '0x2::clock::Clock'],
            ['self', 'balanceManager', 'tradeProof', 'orderId', 'newQuantity']),
      );
}

/// Cancel an order. The order must be owned by the balance_manager. The order is
/// removed from the book and the balance_manager's open orders. The
/// balance_manager's balance is updated with the order's remaining quantity. Order
/// canceled event is emitted.
MoveCallBuilder cancelOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::cancel_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'u128', '0x2::clock::Clock'],
            ['self', 'balanceManager', 'tradeProof', 'orderId']),
      );
}

/// Cancel multiple orders within a vector. The orders must be owned by the
/// balance_manager. The orders are removed from the book and the balance_manager's
/// open orders. Order canceled events are emitted. If any order fails to cancel, no
/// orders will be cancelled.
MoveCallBuilder cancelOrders(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::cancel_orders',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'vector<u128>', '0x2::clock::Clock'],
            ['self', 'balanceManager', 'tradeProof', 'orderIds']),
      );
}

/// Cancel a single order, no-op if the order_id is not currently in the
/// balance_manager's open orders (e.g. already filled, cancelled, or not owned by
/// this balance_manager). If the order is present, it must be owned by the
/// balance_manager. On a successful cancel the order is removed from the book and
/// the balance_manager's open orders, and an order canceled event is emitted.
MoveCallBuilder cancelLiveOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::cancel_live_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'u128', '0x2::clock::Clock'],
            ['self', 'balanceManager', 'tradeProof', 'orderId']),
      );
}

/// Cancel multiple orders within a vector, skipping any order_id that is not
/// currently in the balance_manager's open orders (e.g. already filled, cancelled,
/// or not owned by this balance_manager). Orders that are present must be owned by
/// the balance_manager. The live orders are removed from the book and the
/// balance_manager's open orders. Order canceled events are emitted for each
/// cancelled order.
MoveCallBuilder cancelLiveOrders(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::cancel_live_orders',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'vector<u128>', '0x2::clock::Clock'],
            ['self', 'balanceManager', 'tradeProof', 'orderIds']),
      );
}

/// Cancel all open orders placed by the balance manager in the pool.
MoveCallBuilder cancelAllOrders(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::cancel_all_orders',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, '0x2::clock::Clock'],
            ['self', 'balanceManager', 'tradeProof']),
      );
}

/// Withdraw settled amounts to the `balance_manager`.
MoveCallBuilder withdrawSettledAmounts(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::withdraw_settled_amounts',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, null],
            ['self', 'balanceManager', 'tradeProof']),
      );
}

/// Withdraw settled amounts permissionlessly to the `balance_manager`.
MoveCallBuilder withdrawSettledAmountsPermissionless(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::withdraw_settled_amounts_permissionless',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'balanceManager']),
      );
}

/// Stake DEEP tokens to the pool. The balance_manager must have enough DEEP tokens.
/// The balance_manager's data is updated with the staked amount.
MoveCallBuilder stake(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::stake',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, 'u64'],
            ['self', 'balanceManager', 'tradeProof', 'amount']),
      );
}

/// Unstake DEEP tokens from the pool. The balance_manager must have enough staked
/// DEEP tokens. The balance_manager's data is updated with the unstaked amount.
/// Balance is transferred to the balance_manager immediately.
MoveCallBuilder unstake(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::unstake',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, null],
            ['self', 'balanceManager', 'tradeProof']),
      );
}

/// Submit a proposal to change the taker fee, maker fee, and stake required. The
/// balance_manager must have enough staked DEEP tokens to participate. Each
/// balance_manager can only submit one proposal per epoch. If the maximum proposal
/// is reached, the proposal with the lowest vote is removed. If the balance_manager
/// has less voting power than the lowest voted proposal, the proposal is not added.
MoveCallBuilder submitProposal(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::submit_proposal',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          null,
          'u64',
          'u64',
          'u64'
        ], [
          'self',
          'balanceManager',
          'tradeProof',
          'takerFee',
          'makerFee',
          'stakeRequired'
        ]),
      );
}

/// Vote on a proposal. The balance_manager must have enough staked DEEP tokens to
/// participate. Full voting power of the balance_manager is used. Voting for a new
/// proposal will remove the vote from the previous proposal.
MoveCallBuilder vote(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::vote',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, null, '0x2::object::ID'],
            ['self', 'balanceManager', 'tradeProof', 'proposalId']),
      );
}

/// Claim the rewards for the balance_manager. The balance_manager must have rewards
/// to claim. The balance_manager's data is updated with the claimed rewards.
MoveCallBuilder claimRebates(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::claim_rebates',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, null],
            ['self', 'balanceManager', 'tradeProof']),
      );
}

/// Borrow base assets from the Pool. A hot potato is returned, forcing the borrower
/// to return the assets within the same transaction.
MoveCallBuilder borrowFlashloanBase(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::borrow_flashloan_base',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, 'u64'], ['self', 'baseAmount']),
      );
}

/// Borrow quote assets from the Pool. A hot potato is returned, forcing the
/// borrower to return the assets within the same transaction.
MoveCallBuilder borrowFlashloanQuote(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::borrow_flashloan_quote',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, 'u64'], ['self', 'quoteAmount']),
      );
}

/// Return the flashloaned base assets to the Pool. FlashLoan object will only be
/// unwrapped if the assets are returned, otherwise the transaction will fail.
MoveCallBuilder returnFlashloanBase(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::return_flashloan_base',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null, null], ['self', 'coin', 'flashLoan']),
      );
}

/// Return the flashloaned quote assets to the Pool. FlashLoan object will only be
/// unwrapped if the assets are returned, otherwise the transaction will fail.
MoveCallBuilder returnFlashloanQuote(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::return_flashloan_quote',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null, null], ['self', 'coin', 'flashLoan']),
      );
}

/// Adds a price point along with a timestamp to the deep price. Allows for the
/// calculation of deep price per base asset.
MoveCallBuilder addDeepPricePoint(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::add_deep_price_point',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments,
            [null, null, '0x2::clock::Clock'], ['targetPool', 'referencePool']),
      );
}

/// Burns DEEP tokens from the pool. Amount to burn is within history
MoveCallBuilder burnDeep(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::burn_deep',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'treasuryCap']),
      );
}

/// Mint a DeepBookReferral and set the additional bps for the referral.
MoveCallBuilder mintReferral(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::mint_referral',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, 'u64'], ['self', 'multiplier']),
      );
}

MoveCallBuilder updateReferralMultiplier(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::update_referral_multiplier',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, 'u64'],
            ['Self', 'Referral', 'Multiplier']),
      );
}

MoveCallBuilder updateDeepbookReferralMultiplier(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::update_deepbook_referral_multiplier',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, 'u64'],
            ['Self', 'Referral', 'Multiplier']),
      );
}

/// Update the multiplier for the referral.
MoveCallBuilder updatePoolReferralMultiplier(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::update_pool_referral_multiplier',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, null, 'u64'],
            ['self', 'referral', 'multiplier']),
      );
}

MoveCallBuilder claimReferralRewards(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::claim_referral_rewards',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['Self', 'Referral']),
      );
}

/// Claim the rewards for the referral.
MoveCallBuilder claimPoolReferralRewards(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::claim_pool_referral_rewards',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'referral']),
      );
}

/// Create a new pool. The pool is registered in the registry. Checks are performed
/// to ensure the tick size, lot size, and min size are valid. Returns the id of the
/// pool created
MoveCallBuilder createPoolAdmin(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::create_pool_admin',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          'u64',
          'u64',
          'u64',
          'bool',
          'bool',
          null
        ], [
          'registry',
          'tickSize',
          'lotSize',
          'minSize',
          'whitelistedPool',
          'stablePool',
          'Cap'
        ]),
      );
}

/// Unregister a pool in case it needs to be redeployed.
MoveCallBuilder unregisterPoolAdmin(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::unregister_pool_admin',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null, null], ['self', 'registry', 'Cap']),
      );
}

/// Takes the registry and updates the allowed version within pool Only admin can
/// update the allowed versions This function does not have version restrictions
MoveCallBuilder updateAllowedVersions(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::update_allowed_versions',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null, null], ['self', 'registry', 'Cap']),
      );
}

/// Takes the registry and updates the allowed version within pool Permissionless
/// equivalent of `update_allowed_versions` This function does not have version
/// restrictions
MoveCallBuilder updatePoolAllowedVersions(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::update_pool_allowed_versions',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'registry']),
      );
}

/// Adjust the tick size of the pool. Only admin can adjust the tick size.
MoveCallBuilder adjustTickSizeAdmin(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::adjust_tick_size_admin',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, 'u64', null, '0x2::clock::Clock'],
            ['self', 'newTickSize', 'Cap']),
      );
}

/// Adjust and lot size and min size of the pool. New lot size must be smaller than
/// current lot size. Only admin can adjust the min size and lot size.
MoveCallBuilder adjustMinLotSizeAdmin(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::adjust_min_lot_size_admin',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, 'u64', 'u64', null, '0x2::clock::Clock'],
            ['self', 'newLotSize', 'newMinSize', 'Cap']),
      );
}

/// Enable the EWMA state for the pool. This allows the pool to use the EWMA state
/// for volatility calculations and additional taker fees.
MoveCallBuilder enableEwmaState(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::enable_ewma_state',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, 'bool', '0x2::clock::Clock'],
            ['self', 'Cap', 'enable']),
      );
}

/// Set the EWMA parameters for the pool. Only admin can set the parameters.
MoveCallBuilder setEwmaParams(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::set_ewma_params',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, 'u64', 'u64', 'u64', '0x2::clock::Clock'],
            ['self', 'Cap', 'alpha', 'zScoreThreshold', 'additionalTakerFee']),
      );
}

/// Accessor to check if the pool is whitelisted.
MoveCallBuilder whitelisted(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::whitelisted',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Accessor to check if the pool is a stablecoin pool.
MoveCallBuilder stablePool(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::stable_pool',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder registeredPool(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::registered_pool',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Dry run to determine the quote quantity out for a given base quantity. Uses DEEP
/// token as fee.
MoveCallBuilder getQuoteQuantityOut(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_quote_quantity_out',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments,
            [null, 'u64', '0x2::clock::Clock'], ['self', 'baseQuantity']),
      );
}

/// Dry run to determine the base quantity out for a given quote quantity. Uses DEEP
/// token as fee.
MoveCallBuilder getBaseQuantityOut(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_base_quantity_out',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments,
            [null, 'u64', '0x2::clock::Clock'], ['self', 'quoteQuantity']),
      );
}

/// Dry run to determine the quote quantity out for a given base quantity. Uses
/// input token as fee.
MoveCallBuilder getQuoteQuantityOutInputFee(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_quote_quantity_out_input_fee',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments,
            [null, 'u64', '0x2::clock::Clock'], ['self', 'baseQuantity']),
      );
}

/// Dry run to determine the base quantity out for a given quote quantity. Uses
/// input token as fee.
MoveCallBuilder getBaseQuantityOutInputFee(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_base_quantity_out_input_fee',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments,
            [null, 'u64', '0x2::clock::Clock'], ['self', 'quoteQuantity']),
      );
}

/// Dry run to determine the quantity out for a given base or quote quantity. Only
/// one out of base or quote quantity should be non-zero. Returns the
/// (base_quantity_out, quote_quantity_out, deep_quantity_required) Uses DEEP token
/// as fee.
MoveCallBuilder getQuantityOut(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_quantity_out',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, 'u64', 'u64', '0x2::clock::Clock'],
            ['self', 'baseQuantity', 'quoteQuantity']),
      );
}

/// Dry run to determine the quantity out for a given base or quote quantity. Only
/// one out of base or quote quantity should be non-zero. Returns the
/// (base_quantity_out, quote_quantity_out, deep_quantity_required) Uses input token
/// as fee.
MoveCallBuilder getQuantityOutInputFee(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_quantity_out_input_fee',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, 'u64', 'u64', '0x2::clock::Clock'],
            ['self', 'baseQuantity', 'quoteQuantity']),
      );
}

/// Dry run to determine the base quantity needed to sell to receive a target quote
/// quantity. Returns (base_quantity_in, actual_quote_quantity_out,
/// deep_quantity_required) Returns (0, 0, 0) if insufficient liquidity or if result
/// would be below min_size.
MoveCallBuilder getBaseQuantityIn(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_base_quantity_in',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, 'u64', 'bool', '0x2::clock::Clock'],
            ['self', 'targetQuoteQuantity', 'payWithDeep']),
      );
}

/// Dry run to determine the quote quantity needed to buy a target base quantity.
/// Returns (actual_base_quantity_out, quote_quantity_in, deep_quantity_required)
/// Returns (0, 0, 0) if insufficient liquidity or if result would be below
/// min_size.
MoveCallBuilder getQuoteQuantityIn(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_quote_quantity_in',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, 'u64', 'bool', '0x2::clock::Clock'],
            ['self', 'targetBaseQuantity', 'payWithDeep']),
      );
}

/// Returns the mid price of the pool.
MoveCallBuilder midPrice(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::mid_price',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, '0x2::clock::Clock'], ['self']),
      );
}

/// Top-of-book read for PTB construction / devInspect (SDK, UI). Returns the best
/// (lowest) ask price, skipping expired orders. Returns `none` if the ask side has
/// no live order.
MoveCallBuilder bestAskPrice(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::best_ask_price',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, '0x2::clock::Clock'], ['self']),
      );
}

/// Top-of-book read for PTB construction / devInspect (SDK, UI). Returns the best
/// (highest) bid price, skipping expired orders. Returns `none` if the bid side has
/// no live order.
MoveCallBuilder bestBidPrice(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::best_bid_price',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, '0x2::clock::Clock'], ['self']),
      );
}

/// Returns the order_id for all open order for the balance_manager in the pool.
MoveCallBuilder accountOpenOrders(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::account_open_orders',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'balanceManager']),
      );
}

/// Returns the (price_vec, quantity_vec) for the level2 order book. The price_low
/// and price_high are inclusive, all orders within the range are returned. is_bid
/// is true for bids and false for asks.
MoveCallBuilder getLevel2Range(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_level2_range',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, 'u64', 'u64', 'bool', '0x2::clock::Clock'],
            ['self', 'priceLow', 'priceHigh', 'isBid']),
      );
}

/// Returns the (price_vec, quantity_vec) for the level2 order book. Ticks are the
/// maximum number of ticks to return starting from best bid and best ask.
/// (bid_price, bid_quantity, ask_price, ask_quantity) are returned as 4 vectors.
/// The price vectors are sorted in descending order for bids and ascending order
/// for asks.
MoveCallBuilder getLevel2TicksFromMid(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_level2_ticks_from_mid',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments,
            [null, 'u64', '0x2::clock::Clock'], ['self', 'ticks']),
      );
}

/// Get all balances held in this pool.
MoveCallBuilder vaultBalances(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::vault_balances',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Get the ID of the pool given the asset types.
MoveCallBuilder getPoolIdByAsset(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_pool_id_by_asset',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['registry']),
      );
}

/// Get the Order struct
MoveCallBuilder getOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, 'u128'], ['self', 'orderId']),
      );
}

/// Get multiple orders given a vector of order_ids.
MoveCallBuilder getOrders(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_orders',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, 'vector<u128>'], ['self', 'orderIds']),
      );
}

/// Return a copy of all orders that are in the book for this account.
MoveCallBuilder getAccountOrderDetails(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_account_order_details',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'balanceManager']),
      );
}

/// Return the DEEP price for the pool.
MoveCallBuilder getOrderDeepPrice(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_order_deep_price',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Returns the deep required for an order if it's taker or maker given quantity and
/// price Does not account for discounted taker fees Returns (deep_required_taker,
/// deep_required_maker)
MoveCallBuilder getOrderDeepRequired(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_order_deep_required',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null, 'u64', 'u64'],
            ['self', 'baseQuantity', 'price']),
      );
}

/// Returns the locked balance for the balance_manager in the pool Returns
/// (base_quantity, quote_quantity, deep_quantity)
MoveCallBuilder lockedBalance(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::locked_balance',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'balanceManager']),
      );
}

/// Check if a limit order can be placed based on balance manager balances. Returns
/// true if the balance manager has sufficient balance (accounting for fees) to
/// place the order, false otherwise. Assumes the limit order is a taker order as a
/// worst case scenario.
MoveCallBuilder canPlaceLimitOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::can_place_limit_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [
          null,
          null,
          'u64',
          'u64',
          'bool',
          'bool',
          'u64',
          '0x2::clock::Clock'
        ], [
          'self',
          'balanceManager',
          'price',
          'quantity',
          'isBid',
          'payWithDeep',
          'expireTimestamp'
        ]),
      );
}

/// Check if a market order can be placed based on balance manager balances. Returns
/// true if the balance manager has sufficient balance (accounting for fees) to
/// place the order, false otherwise. Does not account for discounted taker fees
MoveCallBuilder canPlaceMarketOrder(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::can_place_market_order',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, null, 'u64', 'bool', 'bool', '0x2::clock::Clock'],
            ['self', 'balanceManager', 'quantity', 'isBid', 'payWithDeep']),
      );
}

/// Check if a market order can be placed based on pool book params. Returns true if
/// the order parameters are valid, false otherwise.
MoveCallBuilder checkMarketOrderParams(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::check_market_order_params',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, 'u64'], ['self', 'quantity']),
      );
}

/// Check if a limit order can be placed based on pool book params. Returns true if
/// the order parameters are valid, false otherwise.
MoveCallBuilder checkLimitOrderParams(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::check_limit_order_params',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx,
            arguments,
            [null, 'u64', 'u64', 'u64', '0x2::clock::Clock'],
            ['self', 'price', 'quantity', 'expireTimestamp']),
      );
}

/// Returns the trade params for the pool. Returns (taker_fee, maker_fee,
/// stake_required)
MoveCallBuilder poolTradeParams(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::pool_trade_params',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Returns the currently leading trade params for the next epoch for the pool
MoveCallBuilder poolTradeParamsNext(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::pool_trade_params_next',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Returns the tick size, lot size, and min size for the pool.
MoveCallBuilder poolBookParams(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::pool_book_params',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder accountExists(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::account_exists',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'balanceManager']),
      );
}

MoveCallBuilder account(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::account',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'balanceManager']),
      );
}

/// Returns the quorum needed to pass proposal in the current epoch
MoveCallBuilder quorum(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::quorum',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder id(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::id',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

MoveCallBuilder getReferralBalances(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_referral_balances',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['Self', 'Referral']),
      );
}

MoveCallBuilder getPoolReferralBalances(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::get_pool_referral_balances',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'referral']),
      );
}

MoveCallBuilder poolReferralMultiplier(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::pool::pool_referral_multiplier',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'referral']),
      );
}
