// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/sui/versioned.dart' as versioned;
import './deps/sui/vec_set.dart' as vec_set;
import './deps/sui/bag.dart' as bag;
import './deps/std/type_name.dart' as type_name;

const $moduleName = '@deepbook/core::registry';

final REGISTRY = Bcs.struct('${$moduleName}::REGISTRY', {
  'dummy_field': SuiBcs.BOOL,
});

final DeepbookAdminCap = Bcs.struct('${$moduleName}::DeepbookAdminCap', {
  'id': SuiBcs.Address,
});

final DeepbookCorePauseCap =
    Bcs.struct('${$moduleName}::DeepbookCorePauseCap', {
  'id': SuiBcs.Address,
});

final Registry = Bcs.struct('${$moduleName}::Registry', {
  'id': SuiBcs.Address,
  'inner': versioned.Versioned,
});

final RegistryInner = Bcs.struct('${$moduleName}::RegistryInner', {
  'allowed_versions': vec_set.VecSet(SuiBcs.U64),
  'pools': bag.Bag,
  'treasury_address': SuiBcs.Address,
});

final PoolKey = Bcs.struct('${$moduleName}::PoolKey', {
  'base': type_name.TypeName,
  'quote': type_name.TypeName,
});

final StableCoinKey = Bcs.struct('${$moduleName}::StableCoinKey', {
  'dummy_field': SuiBcs.BOOL,
});

final BalanceManagerKey = Bcs.struct('${$moduleName}::BalanceManagerKey', {
  'dummy_field': SuiBcs.BOOL,
});

final AllowedPauseCapsKey = Bcs.tuple(
    [SuiBcs.BOOL], BcsTypeOptions(name: '${$moduleName}::AllowedPauseCapsKey'));

final AppKey = Bcs.struct('${$moduleName}::AppKey<phantom App>', {
  'dummy_field': SuiBcs.BOOL,
});

final AppKeyV2 = Bcs.struct('${$moduleName}::AppKeyV2<phantom App>', {
  'dummy_field': SuiBcs.BOOL,
});

/// Authorize an application to access protected features of the DeepBook.
MoveCallBuilder authorizeApp(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::registry::authorize_app',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'AdminCap']),
      );
}

/// Deauthorize an application by removing its authorization key.
MoveCallBuilder deauthorizeApp(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::registry::deauthorize_app',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'AdminCap']),
      );
}

/// Assert that an application is authorized to access protected features of
/// DeepBook.
MoveCallBuilder assertAppIsAuthorized(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::registry::assert_app_is_authorized',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Sets the treasury address where the pool creation fees are sent By default, the
/// treasury address is the publisher of the deepbook package
MoveCallBuilder setTreasuryAddress(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::registry::set_treasury_address',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, 'address', null], ['self', 'treasuryAddress', 'Cap']),
      );
}

/// Enables a package version Only Admin can enable a package version This function
/// does not have version restrictions
MoveCallBuilder enableVersion({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::registry::enable_version',
        arguments: normalizeMoveArguments(
            tx, arguments, [null, 'u64', null], ['self', 'version', 'Cap']),
      );
}

/// Disables a package version Only Admin can disable a package version This
/// function does not have version restrictions
MoveCallBuilder disableVersion({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::registry::disable_version',
        arguments: normalizeMoveArguments(
            tx, arguments, [null, 'u64', null], ['self', 'version', 'Cap']),
      );
}

/// Mint a `DeepbookCorePauseCap`. The new cap's ID is recorded so it can later
/// disable a version via `disable_version_pause_cap`. Only Admin can mint. This
/// function does not have version restrictions.
MoveCallBuilder mintPauseCap({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::registry::mint_pause_cap',
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'Cap']),
      );
}

/// Revoke a previously minted pause cap by ID. Only Admin can revoke. This function
/// does not have version restrictions.
MoveCallBuilder revokePauseCap({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::registry::revoke_pause_cap',
        arguments: normalizeMoveArguments(tx, arguments,
            [null, null, '0x2::object::ID'], ['self', 'Cap', 'pauseCapId']),
      );
}

/// Disable any allowed package version (including the current one) using a valid
/// `DeepbookCorePauseCap`. The pause cap must be in `allowed_pause_caps`. This
/// function is the emergency kill switch; admin can re-enable via `enable_version`.
/// This function does not have version restrictions.
MoveCallBuilder disableVersionPauseCap(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::registry::disable_version_pause_cap',
        arguments: normalizeMoveArguments(tx, arguments, [null, 'u64', null],
            ['self', 'version', 'pauseCap']),
      );
}

/// Adds a stablecoin to the whitelist Only Admin can add stablecoin
MoveCallBuilder addStablecoin(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::registry::add_stablecoin',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'Cap']),
      );
}

/// Removes a stablecoin from the whitelist Only Admin can remove stablecoin
MoveCallBuilder removeStablecoin(
    {required dynamic arguments,
    String? package,
    List<String> typeArguments = const []}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::registry::remove_stablecoin',
        typeArguments: typeArguments,
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'Cap']),
      );
}

/// Adds the BalanceManagerKey dynamic field to the registry
MoveCallBuilder initBalanceManagerMap(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::registry::init_balance_manager_map',
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'Cap']),
      );
}

/// Get the balance manager IDs for a given owner
MoveCallBuilder getBalanceManagerIds(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::registry::get_balance_manager_ids',
        arguments: normalizeMoveArguments(
            tx, arguments, [null, 'address'], ['self', 'owner']),
      );
}

/// Get the set of pause cap IDs allowed to disable package versions. Returns an
/// empty set if no pause caps have been minted yet.
MoveCallBuilder allowedPauseCaps(
    {required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::registry::allowed_pause_caps',
        arguments: normalizeMoveArguments(tx, arguments, [null], ['self']),
      );
}

/// Returns whether the given coin is whitelisted
MoveCallBuilder isStablecoin({required dynamic arguments, String? package}) {
  final packageAddress = package ?? '@deepbook/core';
  return (tx) => tx.moveCall(
        '$packageAddress::registry::is_stablecoin',
        arguments: normalizeMoveArguments(
            tx, arguments, [null, null], ['self', 'stableType']),
      );
}
