// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/sui/table.dart' as table;
import './history.dart' as history;
import './governance.dart' as governance;
import './balances.dart' as balances;

const $moduleName = '@deepbook/core::state';

final State = Bcs.struct('${$moduleName}::State', {
  'accounts': table.Table,
  'history': history.History,
  'governance': governance.Governance,
});

final StakeEvent = Bcs.struct('${$moduleName}::StakeEvent', {
  'pool_id': SuiBcs.Address,
  'balance_manager_id': SuiBcs.Address,
  'epoch': SuiBcs.U64,
  'amount': SuiBcs.U64,
  'stake': SuiBcs.BOOL,
});

final ProposalEvent = Bcs.struct('${$moduleName}::ProposalEvent', {
  'pool_id': SuiBcs.Address,
  'balance_manager_id': SuiBcs.Address,
  'epoch': SuiBcs.U64,
  'taker_fee': SuiBcs.U64,
  'maker_fee': SuiBcs.U64,
  'stake_required': SuiBcs.U64,
});

final VoteEvent = Bcs.struct('${$moduleName}::VoteEvent', {
  'pool_id': SuiBcs.Address,
  'balance_manager_id': SuiBcs.Address,
  'epoch': SuiBcs.U64,
  'from_proposal_id': Bcs.option(SuiBcs.Address),
  'to_proposal_id': SuiBcs.Address,
  'stake': SuiBcs.U64,
});

final RebateEventV2 = Bcs.struct('${$moduleName}::RebateEventV2', {
  'pool_id': SuiBcs.Address,
  'balance_manager_id': SuiBcs.Address,
  'epoch': SuiBcs.U64,
  'claim_amount': balances.Balances,
});

final RebateEvent = Bcs.struct('${$moduleName}::RebateEvent', {
  'pool_id': SuiBcs.Address,
  'balance_manager_id': SuiBcs.Address,
  'epoch': SuiBcs.U64,
  'claim_amount': SuiBcs.U64,
});

final TakerFeePenaltyApplied =
    Bcs.struct('${$moduleName}::TakerFeePenaltyApplied', {
  'pool_id': SuiBcs.Address,
  'balance_manager_id': SuiBcs.Address,
  'order_id': SuiBcs.U128,
  'taker_fee_without_penalty': SuiBcs.U64,
  'taker_fee': SuiBcs.U64,
});
