// GENERATED by tool/codegen/generate.dart — DO NOT EDIT BY HAND.
// Source: @mysten/deepbook-v3 src/contracts (see DEEPBOOK_MIGRATION_PLAN.md
// for the pinned upstream commit). Regenerate with:
//   dart tool/codegen/generate.dart <ts-sdks>/packages/deepbook-v3/src/contracts
// ignore_for_file: non_constant_identifier_names, unused_import

import 'package:bcs/bcs.dart';
import 'package:sui/bcs/sui_bcs.dart';
import 'package:sui/sui.dart' show Transaction;
import '../utils.dart';
import './deps/sui/balance.dart' as balance;
import './deps/std/type_name.dart' as type_name;

const $moduleName = '@deepbook/core::vault';

final Vault =
    Bcs.struct('${$moduleName}::Vault<phantom BaseAsset, phantom QuoteAsset>', {
  'base_balance': balance.Balance,
  'quote_balance': balance.Balance,
  'deep_balance': balance.Balance,
});

final FlashLoan = Bcs.struct('${$moduleName}::FlashLoan', {
  'pool_id': SuiBcs.Address,
  'borrow_quantity': SuiBcs.U64,
  'type_name': type_name.TypeName,
});

final FlashLoanBorrowed = Bcs.struct('${$moduleName}::FlashLoanBorrowed', {
  'pool_id': SuiBcs.Address,
  'borrow_quantity': SuiBcs.U64,
  'type_name': type_name.TypeName,
});
